In [1]:
import pandas as pd

In [4]:
#Series Creation
d = pd.Series([1,2,3,4],name = "sales")
d

0    1
1    2
2    3
3    4
Name: sales, dtype: int64

In [6]:
# Custom Index Example

In [8]:
s = pd.Series([100,200,300,400],index = ["jan","feb","mar","apr"],name = "Revenue")
s

jan    100
feb    200
mar    300
apr    400
Name: Revenue, dtype: int64

## DataFrame Creation

In [10]:
data = {
        "Name": ["Ravi", "Sita", "Amit", "Neha"],
    "Age": [25, 30, 28, 22],
    "Department": ["IT", "HR", "Finance", "IT"]
}
df1 = pd.DataFrame(data)
df1

   Name  Age Department
0  Ravi   25         IT
1  Sita   30         HR
2  Amit   28    Finance
3  Neha   22         IT

In [11]:
df2 = pd.DataFrame(
    {"Name": ["Ravi", "Sita", "Amit", "Neha"],
    "Age": [25, 30, 28, 22],
    "Department": ["IT", "HR", "Finance", "IT"]}
)
df2

   Name  Age Department
0  Ravi   25         IT
1  Sita   30         HR
2  Amit   28    Finance
3  Neha   22         IT

#.head() and .tail()

In [12]:
print(df1.head(2))

   Name  Age Department
0  Ravi   25         IT
1  Sita   30         HR

In [13]:
print(df1.tail(2))

   Name  Age Department
2  Amit   28    Finance
3  Neha   22         IT

In [ ]:
print(df1.info())

## .astype() – Convert Data Types

### Syntax df["column"] = df["column"].astype(new_dtype)

In [17]:
data = {"ID": ["1", "2", "3"], "Salary": ["50000", "60000", "45000"]}
df = pd.DataFrame(data)
print(df.dtypes)

ID        object
Salary    object
dtype: object

In [20]:
df["ID"] = df["ID"].astype(int)
df["Salary"] = df["Salary"].astype(float)
print(df.dtypes)

ID          int32
Salary    float64
dtype: object

### pd.to_datetime() – Date Conversion

In [26]:
dates = pd.Series(["2023-01-10", "2023/02/15", "March 5, 2023"])
dt = pd.to_datetime(dates,format = 'mixed')
print(dt)

0   2023-01-10
1   2023-02-15
2   2023-03-05
dtype: datetime64[ns]

### CSV Load + Type Conversion (Exercise Style)

In [28]:
df = pd.read_csv("employees.csv")
df

   EmpID   Name JoiningDate  Salary Department
0      1   Ravi  2021-05-10   50000         IT
1      2   Sita  2022-07-15   60000         HR
2      3   Amit  2021-08-01   55000    Finance
3      4   Neha  2023-01-20   48000         IT
4      5  Arjun  2020-11-11   75000    Finance
5      6  Meera  2019-03-25   42000         HR
6      7  Karan  2021-12-05   58000         IT
7      8  Pooja  2022-09-30   67000    Finance

In [27]:
df = pd.read_csv("employees.csv")
print(df.dtypes)

EmpID           int64
Name           object
JoiningDate    object
Salary          int64
Department     object
dtype: object

In [32]:
df["EmpID"] = df["EmpID"].astype("Int64")
df["Salary"] = df["Salary"].astype("float32")
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])
df["Department"] = df["Department"].astype("category")

In [33]:
print(df.dtypes)

EmpID                   Int64
Name                   object
JoiningDate    datetime64[ns]
Salary                float32
Department           category
dtype: object

In [36]:
df["joining_Year"] = df["JoiningDate"].dt.year
df["joining_Month"] = df["JoiningDate"].dt.month
df

   EmpID   Name JoiningDate   Salary Department  joining_Year  joining_Month
0      1   Ravi  2021-05-10  50000.0         IT          2021              5
1      2   Sita  2022-07-15  60000.0         HR          2022              7
2      3   Amit  2021-08-01  55000.0    Finance          2021              8
3      4   Neha  2023-01-20  48000.0         IT          2023              1
4      5  Arjun  2020-11-11  75000.0    Finance          2020             11
5      6  Meera  2019-03-25  42000.0         HR          2019              3
6      7  Karan  2021-12-05  58000.0         IT          2021             12
7      8  Pooja  2022-09-30  67000.0    Finance          2022              9

In [37]:
average_salary = df["Salary"].mean()
average_salary

56875.0