In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('employees.csv')
print(df)

     emp_id             name   age  gender   department designation    salary  \
0      1001     Kriti Saxena  33.0    Male  Engineering     Manager  133646.0
1      1002      Aadhya Nair  39.0  Female  Engineering      Senior   81835.0
2      1003    Bhavna Saxena  56.0    Male  Engineering      Intern   42051.0
3      1004       Rohan Shah  51.0    Male        Sales   Associate   72798.0
4      1005       Geeta Nair  45.0  Female  Engineering      Senior   91113.0
..      ...              ...   ...     ...          ...         ...       ...
500    1501  Pallavi Chauhan  34.0  Female  Engineering      Junior   55135.0
501    1502       Geeta Nair  45.0  Female  Engineering      Senior   91113.0
502    1503    Aditya Mishra  27.0  Female  Engineering      Junior   55060.0
503    1504    Shweta Pillai  41.0  Female        Sales      Senior   88299.0
504    1505    Rakesh Chopra  37.0    Male      Support     Manager  137886.0

        city join_date  experience_years  rating                        email
0      Delhi  25-04-24                10     3.5     kriti.saxena@company.com
1       Pune  24-05-16                15     NaN      aadhya.nair@company.com
2       Pune  28-06-17                34     4.3    bhavna.saxena@company.com
3     Mumbai  11-03-15                30     NaN       rohan.shah@company.com
4    Kolkata  04-03-21                24     3.6       geeta.nair@company.com
..       ...       ...               ...     ...                          ...
500  kolkata  09-10-19                13     3.5  pallavi.chauhan@company.com
501  Kolkata  04-03-21                24     3.6       geeta.nair@company.com
502  Chennai  16-03-18                 5     3.3    aditya.mishra@company.com
503   Mumbai  05-11-23                19     4.4    shweta.pillai@company.com
504    Surat  20-08-19                16     3.0    rakesh.chopra@company.com

[505 rows x 12 columns]

In [4]:
print(df.head(5))

   emp_id           name   age  gender   department designation    salary  \
0    1001   Kriti Saxena  33.0    Male  Engineering     Manager  133646.0
1    1002    Aadhya Nair  39.0  Female  Engineering      Senior   81835.0
2    1003  Bhavna Saxena  56.0    Male  Engineering      Intern   42051.0
3    1004     Rohan Shah  51.0    Male        Sales   Associate   72798.0
4    1005     Geeta Nair  45.0  Female  Engineering      Senior   91113.0

      city join_date  experience_years  rating                      email
0    Delhi  25-04-24                10     3.5   kriti.saxena@company.com
1     Pune  24-05-16                15     NaN    aadhya.nair@company.com
2     Pune  28-06-17                34     4.3  bhavna.saxena@company.com
3   Mumbai  11-03-15                30     NaN     rohan.shah@company.com
4  Kolkata  04-03-21                24     3.6     geeta.nair@company.com

In [5]:
df[['name','age','gender']]

                name   age  gender
0       Kriti Saxena  33.0    Male
1        Aadhya Nair  39.0  Female
2      Bhavna Saxena  56.0    Male
3         Rohan Shah  51.0    Male
4         Geeta Nair  45.0  Female
..               ...   ...     ...
500  Pallavi Chauhan  34.0  Female
501       Geeta Nair  45.0  Female
502    Aditya Mishra  27.0  Female
503    Shweta Pillai  41.0  Female
504    Rakesh Chopra  37.0    Male

[505 rows x 3 columns]

In [14]:
#selecting rows by position(iloc)
df.iloc[0]
df.iloc[0:3]
df.iloc[[0,2,4]]

#rows and columns by position
df.iloc[0:3,0:2]
df.iloc[[0,2,4],[0,2]]
df.iloc[:,0:2]
df.iloc[-3:]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [17]:
#selecting rows by label(loc)
df.loc[0]

#rows and column by label
df.loc[0:2,'name':'gender']
df.loc[0:2,['name','gender']]

            name  gender
0   Kriti Saxena    Male
1    Aadhya Nair  Female
2  Bhavna Saxena    Male