In [1]:
import pandas as pd

In [14]:
df = pd.read_csv('employees.csv')
mask = df['salary'] > 50000
filtered_df = df[mask]
# filtered_df.shape

# print(df[df['department'] == 'Engineering'])

# print(df[df['department'] != 'HR'])
print(df[df['age'] > 35])

     emp_id           name   age  gender   department designation    salary  \
1      1002    Aadhya Nair  39.0  Female  Engineering      Senior   81835.0
2      1003  Bhavna Saxena  56.0    Male  Engineering      Intern   42051.0
3      1004     Rohan Shah  51.0    Male        Sales   Associate   72798.0
4      1005     Geeta Nair  45.0  Female  Engineering      Senior   91113.0
5      1006    Rahul Gupta  51.0    Male      Product          VP  209477.0
..      ...            ...   ...     ...          ...         ...       ...
493    1494   Suresh Verma  41.0  Female  Engineering      Senior   71811.0
498    1499   Karan Mishra  37.0    Male  Engineering          VP  213644.0
501    1502     Geeta Nair  45.0  Female  Engineering      Senior   91113.0
503    1504  Shweta Pillai  41.0  Female        Sales      Senior   88299.0
504    1505  Rakesh Chopra  37.0    Male      Support     Manager  137886.0

          city join_date  experience_years  rating                      email
1         Pune  24-05-16                15     NaN    aadhya.nair@company.com
2         Pune  28-06-17                34     4.3  bhavna.saxena@company.com
3       Mumbai  11-03-15                30     NaN     rohan.shah@company.com
4      Kolkata  04-03-21                24     3.6     geeta.nair@company.com
5    Ahmedabad  26-09-19                29     3.2    rahul.gupta@company.com
..         ...       ...               ...     ...                        ...
493       Pune  10-11-17                20     2.6   suresh.verma@company.com
498     Jaipur  24-10-15                13     2.9   karan.mishra@company.com
501    Kolkata  04-03-21                24     3.6     geeta.nair@company.com
503     Mumbai  05-11-23                19     4.4  shweta.pillai@company.com
504      Surat  20-08-19                16     3.0  rakesh.chopra@company.com

[309 rows x 12 columns]

In [18]:
#Filtering multiple columns
# df[(df['department'] == 'Engineering') & (df['salary'] > 100000) & (df['city'] == 'Delhi')]
df[(df['department'] == 'Engineering') & (df['age']< 45)]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
6,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-24,12,2.8,karan.mishra@company.com
10,1011,Rohan Sharma,28.0,Female,Engineering,Lead,95758.0,Chennai,11-04-21,7,4.0,rohan.sharma@company.com
16,1017,Aadhya Bhat,23.0,Female,Engineering,Senior,89335.0,Delhi,25-10-22,0,4.5,aadhya.bhat@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
490,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-25,9,4.8,ayaan.joshi@company.com
493,1494,Suresh Verma,41.0,Female,Engineering,Senior,71811.0,Pune,10-11-17,20,2.6,suresh.verma@company.com
498,1499,Karan Mishra,37.0,Male,Engineering,VP,213644.0,Jaipur,24-10-15,13,2.9,karan.mishra@company.com
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com

In [22]:
#filtering with isin
cities = ['Mumbai','Delhi','Bangalore']
# df[df['city'].isin(cities)]
df[~df['city'].isin(cities)] #negation of isin


designations = ['Senior','Intern','VP']
df[df["designation"].isin(designations)]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-17,34,4.3,bhavna.saxena@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-19,29,3.2,rahul.gupta@company.com
6,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-24,12,2.8,karan.mishra@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
495,1496,Ritika Pillai,NaN,Male,Engineering,Senior,84063.0,Bangalore,12-02-23,12,3.5,ritika.pillai@company.com
497,1498,Kavya Mishra,28.0,Male,Operations,Senior,85288.0,Surat,30-12-17,5,NaN,kavya.mishra@company.com
498,1499,Karan Mishra,37.0,Male,Engineering,VP,213644.0,Jaipur,24-10-15,13,2.9,karan.mishra@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-21,24,3.6,geeta.nair@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-23,19,4.4,shweta.pillai@company.com

In [25]:
#filteering with between
df[df['age'].between(30,40)]
result = df[df['age'].between(30,40,inclusive="left")]
print(result)

     emp_id             name   age  gender   department designation    salary  \
0      1001     Kriti Saxena  33.0    Male  Engineering     Manager  133646.0
1      1002      Aadhya Nair  39.0  Female  Engineering      Senior   81835.0
6      1007     Karan Mishra  35.0    Male  Engineering      Senior   82266.0
9      1010    Vivaan Bansal  37.0    Male      Support      Senior   94511.0
11     1012      Lata Thakur  35.0  Female        Sales      Junior   49661.0
..      ...              ...   ...     ...          ...         ...       ...
491    1492       Gaurav Rao  36.0    Male      Product   Associate   54359.0
492    1493     Sai Kulkarni  39.0  Female      Product   Associate   48893.0
498    1499     Karan Mishra  37.0    Male  Engineering          VP  213644.0
500    1501  Pallavi Chauhan  34.0  Female  Engineering      Junior   55135.0
504    1505    Rakesh Chopra  37.0    Male      Support     Manager  137886.0

        city join_date  experience_years  rating                        email
0      Delhi  25-04-24                10     3.5     kriti.saxena@company.com
1       Pune  24-05-16                15     NaN      aadhya.nair@company.com
6      Delhi  12-02-24                12     2.8     karan.mishra@company.com
9       Pune  25-01-24                17     5.0    vivaan.bansal@company.com
11    Jaipur  21-02-21                15     1.5      lata.thakur@company.com
..       ...       ...               ...     ...                          ...
491   Mumbai  02-04-18                16     NaN       gaurav.rao@company.com
492  Chennai  13-08-21                19     2.7     sai.kulkarni@company.com
498   Jaipur  24-10-15                13     2.9     karan.mishra@company.com
500  kolkata  09-10-19                13     3.5  pallavi.chauhan@company.com
504    Surat  20-08-19                16     3.0    rakesh.chopra@company.com

[132 rows x 12 columns]

In [ ]:
#filtering with query
result = df.query('department == "Engineering" and age < 45')
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
6,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-24,12,2.8,karan.mishra@company.com
7,1008,Vivaan Chauhan,27.0,Female,HR,Associate,65792.0,Ahmedabad,25-10-22,3,3.5,vivaan.chauhan@company.com
8,1009,Nikhil Patel,24.0,Female,Marketing,Senior,85452.0,Jaipur,14-01-17,1,4.2,nikhil.patel@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
498,1499,Karan Mishra,37.0,Male,Engineering,VP,213644.0,Jaipur,24-10-15,13,2.9,karan.mishra@company.com
499,1500,Sandeep Patel,24.0,Female,NaN,Manager,110504.0,Hyderabad,01-03-23,1,2.5,sandeep.patel@company.com
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [28]:
#what if we want to filter with variables
min_salary = 50000
max_age = 40
result = df.query('salary > @min_salary and age < @max_age')
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-24,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
6,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-24,12,2.8,karan.mishra@company.com
7,1008,Vivaan Chauhan,27.0,Female,HR,Associate,65792.0,Ahmedabad,25-10-22,3,3.5,vivaan.chauhan@company.com
8,1009,Nikhil Patel,24.0,Female,Marketing,Senior,85452.0,Jaipur,14-01-17,1,4.2,nikhil.patel@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
498,1499,Karan Mishra,37.0,Male,Engineering,VP,213644.0,Jaipur,24-10-15,13,2.9,karan.mishra@company.com
499,1500,Sandeep Patel,24.0,Female,NaN,Manager,110504.0,Hyderabad,01-03-23,1,2.5,sandeep.patel@company.com
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-19,13,3.5,pallavi.chauhan@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-19,16,3.0,rakesh.chopra@company.com

In [ ]:
#filtering with string methods
result = df[df['name'].str.contains('Sharma')] #case sensitive search
result = df[df['name'].str.contains('Sharma',case=False)] #case insensitive search
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
10,1011,Rohan Sharma,28.0,Female,Engineering,Lead,95758.0,Chennai,11-04-21,7,4.0,rohan.sharma@company.com
56,1057,Tanvi Sharma,50.0,Female,Engineering,Senior,71432.0,Jaipur,16-11-21,26,2.9,tanvi.sharma@company.com
61,1062,Meera Sharma,44.0,Female,Operations,Associate,60950.0,Kolkata,07-05-20,22,2.9,meera.sharma@company.com
66,1067,Tanvi Sharma,55.0,Male,Finance,Associate,69703.0,NaN,14-11-22,35,3.8,tanvi.sharma@company.com
68,1069,Aditya Sharma,46.0,Female,Sales,Lead,109028.0,Jaipur,12-12-17,26,3.9,aditya.sharma@company.com
91,1092,Dev Sharma,28.0,Male,HR,Senior,76737.0,Chennai,20-10-21,5,3.0,dev.sharma@company.com
124,1125,Isha Sharma,50.0,Female,Engineering,Associate,64233.0,Kolkata,26-02-25,29,2.4,isha.sharma@company.com
144,1145,Vivaan Sharma,44.0,Male,Support,Junior,39369.0,Chennai,18-08-22,22,2.4,vivaan.sharma@company.com
177,1178,Sahil Sharma,49.0,Female,Support,Lead,97905.0,Surat,20-01-24,25,2.2,sahil.sharma@company.com
188,1189,Tanya Sharma,35.0,Female,Engineering,Senior,84874.0,Hyderabad,15-09-16,14,3.4,tanya.sharma@company.com
211,1212,Neha Sharma,46.0,Male,Finance,Senior,75278.0,Surat,25-10-15,22,3.0,neha.sharma@company.com
274,1275,Kavya Sharma,34.0,Male,Sales,Director,171128.0,Kolkata,29-05-24,10,3.2,kavya.sharma@company.com
278,1279,Dhruv Sharma,47.0,Female,Engineering,Manager,112817.0,Jaipur,18-01-20,27,2.5,dhruv.sharma@company.com
348,1349,Shreya Sharma,34.0,Female,Operations,Junior,43622.0,Hyderabad,26-07-16,13,3.6,shreya.sharma@company.com
365,1366,Aadhya Sharma,56.0,Female,HR,Senior,65136.0,Ahmedabad,12-09-17,32,2.8,aadhya.sharma@company.com
381,1382,Sonal Sharma,28.0,Male,Engineering,Senior,71968.0,Jaipur,06-05-24,6,2.9,sonal.sharma@company.com
429,1430,Divya Sharma,38.0,Female,Engineering,Senior,81530.0,Hyderabad,15-12-17,16,4.7,divya.sharma@company.com
455,1456,Sandeep Sharma,28.0,Male,Support,Junior,41169.0,Jaipur,03-12-21,8,3.3,sandeep.sharma@company.com

In [ ]:
result = df[df["name"].str.startswith('A',case= False)] #case insensitive search for names starting with A
#case sensitive

result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-16,15,NaN,aadhya.nair@company.com
16,1017,Aadhya Bhat,23.0,Female,Engineering,Senior,89335.0,Delhi,25-10-22,0,4.5,aadhya.bhat@company.com
21,1022,Aditya Kumar,35.0,Female,Sales,Junior,50979.0,Bangalore,22-05-19,14,4.2,aditya.kumar@company.com
28,1029,Aishwarya Verma,54.0,Female,Engineering,Intern,34581.0,Surat,13-12-15,30,2.3,aishwarya.verma@company.com
31,1032,Ayaan Chopra,35.0,Female,HR,Director,176500.0,Mumbai,28-10-25,14,3.7,ayaan.chopra@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
480,1481,Aadhya Yadav,26.0,Female,Operations,Junior,30192.0,Kolkata,20-10-21,4,3.3,aadhya.yadav@company.com
483,1484,Anvi Shah,31.0,Male,Product,Lead,97816.0,Bangalore,10-07-23,11,3.2,anvi.shah@company.com
485,1486,Anvi Pillai,45.0,Male,Product,Associate,69826.0,Jaipur,02-04-24,25,4.3,anvi.pillai@company.com
490,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-25,9,4.8,ayaan.joshi@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-18,5,3.3,aditya.mishra@company.com

In [33]:
result = df[df["name"].str.contains("Kumar",case = False) & (df['department'] == "Engineering")]
result

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
98,1099,Dev Kumar,26.0,Male,Engineering,Intern,22162.0,Chennai,02-05-23,5,2.6,dev.kumar@company.com
146,1147,Diya Kumar,40.0,Female,Engineering,Senior,87793.0,Kolkata,06-06-20,16,4.3,diya.kumar@company.com
331,1332,Kabir Kumar,32.0,Female,Engineering,Senior,86443.0,Chennai,19-11-18,10,2.8,kabir.kumar@company.com
400,1401,Rakesh Kumar,28.0,Male,Engineering,Lead,105929.0,Jaipur,30-04-24,5,2.5,rakesh.kumar@company.com
421,1422,Vandana Kumar,46.0,Female,Engineering,Senior,91312.0,Surat,01-02-17,26,3.8,vandana.kumar@company.com