Ek naya DataFrame banao jisme sirf CustomerID, Name, aur Sales columns ho.

.head() se top 5 rows aur .tail() se last 3 rows print karo.

.info() aur .shape ka output check karo aur batao kitne non-null values hain.

Sirf Sales column ko Pandas Series banakar uske first 10 values print karo.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("pandas_phase1_practice.csv")
df.head(5)

   CustomerID        Name  Age       City PurchaseDate  Sales     Product
0           1  Customer_1   56    Kolkata   2024-01-01   3247      Laptop
1           2  Customer_2   46    Chennai   2024-01-02   4349      Tablet
2           3  Customer_3   32     Mumbai   2024-01-03   1779  Headphones
3           4  Customer_4   25  Bangalore   2024-01-04   3606      Mobile
4           5  Customer_5   38      Delhi   2024-01-05   7353  Headphones

In [4]:
df.tail(5)

     CustomerID          Name  Age       City PurchaseDate  Sales     Product
195         196  Customer_196   23      Delhi   2024-07-14   3684      Camera
196         197  Customer_197   49    Kolkata   2024-07-15   9688  Headphones
197         198  Customer_198   21    Kolkata   2024-07-16   8153      Mobile
198         199  Customer_199   28    Kolkata   2024-07-17   3430      Laptop
199         200  Customer_200   34  Bangalore   2024-07-18   2803      Laptop

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    200 non-null    int64
 1   Name          200 non-null    object
 2   Age           200 non-null    int64
 3   City          200 non-null    object
 4   PurchaseDate  200 non-null    object
 5   Sales         200 non-null    int64
 6   Product       200 non-null    object
dtypes: int64(3), object(4)
memory usage: 11.1+ KB

In [12]:
df.shape

(200, 7)

In [14]:
sales_series = df["Sales"]
sales_series.head()

0    3247
1    4349
2    1779
3    3606
4    7353
Name: Sales, dtype: int64

Day 2: Data types (astype()), conversions (pd.to_datetime())

CustomerID ko string me convert karo.

Sales ko float me convert karo aur verify karo dtype.

PurchaseDate ko datetime me convert karke sirf year aur month nikal ke alag column banao.

Check karo Age column ka dtype aur use string me convert karke pehle 5 rows print karo.

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    200 non-null    int64
 1   Name          200 non-null    object
 2   Age           200 non-null    int64
 3   City          200 non-null    object
 4   PurchaseDate  200 non-null    object
 5   Sales         200 non-null    int64
 6   Product       200 non-null    object
dtypes: int64(3), object(4)
memory usage: 11.1+ KB

In [16]:
df["CustomerID"] = df["CustomerID"].astype("float")

In [19]:
df["Sales"] = df["Sales"].astype("float")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    200 non-null    float64
 1   Name          200 non-null    object
 2   Age           200 non-null    int64
 3   City          200 non-null    object
 4   PurchaseDate  200 non-null    object
 5   Sales         200 non-null    float64
 6   Product       200 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 11.1+ KB

In [21]:
df["PurchaseDate"] = pd.to_datetime(df["PurchaseDate"])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    200 non-null    float64
 1   Name          200 non-null    object
 2   Age           200 non-null    int64
 3   City          200 non-null    object
 4   PurchaseDate  200 non-null    datetime64[ns]
 5   Sales         200 non-null    float64
 6   Product       200 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 11.1+ KB

In [23]:
df["Purchase_Month"] = df["PurchaseDate"].dt.month
df["Purchase_Year"] = df["PurchaseDate"].dt.year

In [27]:
df.head(5)

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year
0,1.0,Customer_1,56,Kolkata,2024-01-01,3247.0,Laptop,1,2024
1,2.0,Customer_2,46,Chennai,2024-01-02,4349.0,Tablet,1,2024
2,3.0,Customer_3,32,Mumbai,2024-01-03,1779.0,Headphones,1,2024
3,4.0,Customer_4,25,Bangalore,2024-01-04,3606.0,Mobile,1,2024
4,5.0,Customer_5,38,Delhi,2024-01-05,7353.0,Headphones,1,2024

In [28]:
df["Age"] = df["Age"].astype("float")

In [30]:
df["Age"].head(5)

0    56.0
1    46.0
2    32.0
3    25.0
4    38.0
Name: Age, dtype: float64

Indexing & selection (loc, iloc, slicing)

First 10 rows me se Name aur Sales columns select karo.

iloc use karke row 20 se 30 ke beech ke data nikal ke sirf CustomerID, City print karo.

Slicing karke sirf PurchaseDate aur Sales ka subset banao.

loc use karke CustomerID 50 se 55 tak ka data nikal ke print karo.

In [33]:
df.loc[0:10,["Name","Sales"]]

           Name   Sales
0    Customer_1  3247.0
1    Customer_2  4349.0
2    Customer_3  1779.0
3    Customer_4  3606.0
4    Customer_5  7353.0
5    Customer_6  2844.0
6    Customer_7  9535.0
7    Customer_8  5288.0
8    Customer_9  2241.0
9   Customer_10  6717.0
10  Customer_11  2579.0

In [35]:
df.iloc[20:30,[0,3]]

    CustomerID       City
20        21.0      Delhi
21        22.0      Delhi
22        23.0     Mumbai
23        24.0      Delhi
24        25.0  Bangalore
25        26.0    Chennai
26        27.0      Delhi
27        28.0      Delhi
28        29.0     Mumbai
29        30.0     Mumbai

In [36]:
df.loc[:,["PurchaseDate","Sales"]].head(5)

  PurchaseDate   Sales
0   2024-01-01  3247.0
1   2024-01-02  4349.0
2   2024-01-03  1779.0
3   2024-01-04  3606.0
4   2024-01-05  7353.0

In [37]:
df.loc[50:55]

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year
50,51.0,Customer_51,34.0,Chennai,2024-02-20,2182.0,Tablet,2,2024
51,52.0,Customer_52,53.0,Bangalore,2024-02-21,9067.0,Laptop,2,2024
52,53.0,Customer_53,57.0,Delhi,2024-02-22,6848.0,Camera,2,2024
53,54.0,Customer_54,21.0,Chennai,2024-02-23,9917.0,Laptop,2,2024
54,55.0,Customer_55,19.0,Chennai,2024-02-24,517.0,Mobile,2,2024
55,56.0,Customer_56,23.0,Bangalore,2024-02-25,8406.0,Laptop,2,2024

Day 4: Boolean indexing & multi-condition filters

Un customers ko filter karo jinke Age > 30 hai.

Sirf un customers ko select karo jo City = "Delhi" me hain.

Customers filter karo jinke City = "Delhi" aur Age > 30 hain.

Customers nikal ke dikhao jinke Sales > 8000 ya phir Product = "Laptop" hai.

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      200 non-null    float64
 1   Name            200 non-null    object
 2   Age             200 non-null    float64
 3   City            200 non-null    object
 4   PurchaseDate    200 non-null    datetime64[ns]
 5   Sales           200 non-null    float64
 6   Product         200 non-null    object
 7   Purchase_Month  200 non-null    int32
 8   Purchase_Year   200 non-null    int32
dtypes: datetime64[ns](1), float64(3), int32(2), object(3)
memory usage: 12.6+ KB

In [40]:
df["Age"]  = df["Age"].astype("Int64")

In [48]:
over_thirty = df[df["Age"] > 30].head(4)
over_thirty

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
0,1.0,Customer_1,56,Kolkata,2024-01-01,3247.0,Laptop,1,2024,True
1,2.0,Customer_2,46,Chennai,2024-01-02,4349.0,Tablet,1,2024,True
2,3.0,Customer_3,32,Mumbai,2024-01-03,1779.0,Headphones,1,2024,True
4,5.0,Customer_5,38,Delhi,2024-01-05,7353.0,Headphones,1,2024,True

In [54]:
delhi = df[df["City"]=="Delhi"]
delhi.head(4)

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
4,5.0,Customer_5,38,Delhi,2024-01-05,7353.0,Headphones,1,2024,True
5,6.0,Customer_6,56,Delhi,2024-01-06,2844.0,Headphones,1,2024,True
20,21.0,Customer_21,19,Delhi,2024-01-21,2589.0,Laptop,1,2024,False
21,22.0,Customer_22,38,Delhi,2024-01-22,9923.0,Laptop,1,2024,True

In [57]:
df.query("Age > 30 and City == 'Delhi'").head(5)

C:\Users\gaura\AppData\Local\Temp\ipykernel_2248\1793461541.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query("Age > 30 and City == 'Delhi'").head(5)

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
4,5.0,Customer_5,38,Delhi,2024-01-05,7353.0,Headphones,1,2024,True
5,6.0,Customer_6,56,Delhi,2024-01-06,2844.0,Headphones,1,2024,True
21,22.0,Customer_22,38,Delhi,2024-01-22,9923.0,Laptop,1,2024,True
26,27.0,Customer_27,44,Delhi,2024-01-27,8627.0,Headphones,1,2024,True
27,28.0,Customer_28,59,Delhi,2024-01-28,5978.0,Camera,1,2024,True

In [59]:
#Customers nikal ke dikhao jinke Sales > 8000 ya phir Product = "Laptop" hai.
df.query("Sales > 8000 and Product == 'Laptop'").head(5)

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
21,22.0,Customer_22,38,Delhi,2024-01-22,9923.0,Laptop,1,2024,True
22,23.0,Customer_23,50,Mumbai,2024-01-23,9307.0,Laptop,1,2024,True
34,35.0,Customer_35,38,Chennai,2024-02-04,9860.0,Laptop,2,2024,True
51,52.0,Customer_52,53,Bangalore,2024-02-21,9067.0,Laptop,2,2024,True
53,54.0,Customer_54,21,Chennai,2024-02-23,9917.0,Laptop,2,2024,False

Sorting (sort_values, sort_index), Sampling (sample())

Sales ke hisaab se top 10 customers nikal ke print karo.

Age ke hisaab se ascending aur descending dono order me DataFrame sort karo.

CustomerID ke basis pe sort karke first 5 rows print karo.

Random 100 rows sample karke uska average Sales calculate karo.

In [61]:
top10 = df.sort_values(by = "Sales",ascending = False).head(10)
top10

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
79,80.0,Customer_80,32,Bangalore,2024-03-20,9979.0,Laptop,3,2024,True
146,147.0,Customer_147,19,Mumbai,2024-05-26,9972.0,Tablet,5,2024,False
12,13.0,Customer_13,57,Bangalore,2024-01-13,9927.0,Headphones,1,2024,True
21,22.0,Customer_22,38,Delhi,2024-01-22,9923.0,Laptop,1,2024,True
53,54.0,Customer_54,21,Chennai,2024-02-23,9917.0,Laptop,2,2024,False
34,35.0,Customer_35,38,Chennai,2024-02-04,9860.0,Laptop,2,2024,True
62,63.0,Customer_63,27,Mumbai,2024-03-03,9808.0,Camera,3,2024,False
196,197.0,Customer_197,49,Kolkata,2024-07-15,9688.0,Headphones,7,2024,True
143,144.0,Customer_144,24,Chennai,2024-05-23,9680.0,Mobile,5,2024,False
171,172.0,Customer_172,41,Kolkata,2024-06-20,9676.0,Laptop,6,2024,True

In [65]:
#Age ke hisaab se ascending aur descending dono order me DataFrame sort karo.
desc = df.sort_values(by = "Age",ascending = False)
desc.head(5)

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
56,57.0,Customer_57,59,Delhi,2024-02-26,8908.0,Tablet,2,2024,True
27,28.0,Customer_28,59,Delhi,2024-01-28,5978.0,Camera,1,2024,True
128,129.0,Customer_129,59,Bangalore,2024-05-08,6831.0,Mobile,5,2024,True
95,96.0,Customer_96,59,Chennai,2024-04-05,7500.0,Laptop,4,2024,True
147,148.0,Customer_148,59,Mumbai,2024-05-27,8802.0,Tablet,5,2024,True

In [66]:
asc = df.sort_values(by = "Age",ascending = True)
asc.head(5)

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
118,119.0,Customer_119,18,Bangalore,2024-04-28,6641.0,Headphones,4,2024,False
113,114.0,Customer_114,18,Bangalore,2024-04-23,1162.0,Mobile,4,2024,False
80,81.0,Customer_81,18,Bangalore,2024-03-21,6906.0,Laptop,3,2024,False
85,86.0,Customer_86,18,Chennai,2024-03-26,3014.0,Mobile,3,2024,False
190,191.0,Customer_191,18,Delhi,2024-07-09,6290.0,Mobile,7,2024,False

In [67]:
#CustomerID ke basis pe sort karke first 5 rows print karo.

In [68]:
cust_id = df.sort_values(by = "CustomerID",ascending = True).head(5)
cust_id

,CustomerID,Name,Age,City,PurchaseDate,Sales,Product,Purchase_Month,Purchase_Year,over_thirty
0,1.0,Customer_1,56,Kolkata,2024-01-01,3247.0,Laptop,1,2024,True
1,2.0,Customer_2,46,Chennai,2024-01-02,4349.0,Tablet,1,2024,True
2,3.0,Customer_3,32,Mumbai,2024-01-03,1779.0,Headphones,1,2024,True
3,4.0,Customer_4,25,Bangalore,2024-01-04,3606.0,Mobile,1,2024,False
4,5.0,Customer_5,38,Delhi,2024-01-05,7353.0,Headphones,1,2024,True

In [73]:
for_avg = df.sample(n=100,random_state = 42)
avg_sales = for_avg["Sales"].mean()
print(avg_sales)

5514.01