📜 Common Regex Symbols & Meaning
Symbol/Pattern	             Meaning	                    Example
.	           Any single character except newline	    a.b → acb, arb
^	                  Start of string                    	^Hello
$	                   End of string	                    world$
*	             0 or more repetitions	                   a* → aaa
+	             1 or more repetitions	                   a+ → aaa
?	               0 or 1 repetition	                   colou?r → color, colour
{m,n}	      Between m and n repetitions	            a{2,3} → aa, aaa
[]	                     Character set	                   [abc] → a, b, c
[^ ]	                   Negation	                  [^0-9] → Non-digit chars
\d	                      Any digit	                        [0-9]
\D	                      Non-digit	                        [^0-9]
\w	                      Word character	              [a-zA-Z0-9_]
\W	                      Non-word character          Punctuation, space
\s	                      Whitespace	                    space, tab
\S	                      Non-whitespace

In [2]:
import re

# Basic Methods
# re.search(pattern, string)   # Pattern ko search karta hai
# re.match(pattern, string)    # String ke start se match karta hai
# re.findall(pattern, string)  # Sab matches ki list return karta hai
# re.sub(pattern, repl, string)# Pattern ko replace karta hai

In [3]:
text = "I love Python"
pattern = "Python"

result = re.search(pattern, text)
print(result)

<re.Match object; span=(7, 13), match='Python'>

In [6]:
#2. Find All Matches
text = "cat mat bat rat"
matches = re.findall(r"[m]at", text)
print(matches)

['mat']

In [7]:
text = "hello world"
print(re.findall(r"^hello", text)) # Start
print(re.findall(r"world$", text)) # End

['hello']
['world']

In [8]:
text = "My number is 9876543210"
numbers = re.findall(r"\d+", text)
print(numbers)

['9876543210']

In [12]:
import pandas as pd

df = pd.DataFrame({"email": ["test@example.com", "user@yahoo.in", "coder@outlook.com"]})

# Regex lagao
df["whole_domain"] = df["email"].str.extract(r'@([\w]+\.\w+)')
print(df)

               email whole_domain
0   test@example.com  example.com
1      user@yahoo.in     yahoo.in
2  coder@outlook.com  outlook.com

In [13]:
df["whole_domain"]

0    example.com
1       yahoo.in
2    outlook.com
Name: whole_domain, dtype: object

In [17]:
df["domain"] = df["email"].str.extract(r'@([\w]+)')
df

               email whole_domain   domain
0   test@example.com  example.com  example
1      user@yahoo.in     yahoo.in    yahoo
2  coder@outlook.com  outlook.com  outlook

In [28]:
import pandas as pd

data = {
    "email": ["test@example.com", "user@yahoo.in", "coder@outlook.com", "bademail@wrong", "admin@gmail.com"],
    "phone": ["+91-9876543210", "91 8765432109", "(+91) 9998887776", "12345", "0987654321"],
    "name": ["John Doe", "Jane Smith", "Mike O'Neil", "Anna-Marie", "Tom"]
}
df = pd.DataFrame(data)
print(df)

               email             phone         name
0   test@example.com    +91-9876543210     John Doe
1      user@yahoo.in     91 8765432109   Jane Smith
2  coder@outlook.com  (+91) 9998887776  Mike O'Neil
3     bademail@wrong             12345   Anna-Marie
4    admin@gmail.com        0987654321          Tom

## Extract Email Domain (Provider)

Goal: Email ke @ ke baad ka domain nikalna.
Sample: test@example.com → example.com

In [29]:
df["domain"] = df["email"].str.extract(r'@([\w]+\.\w+)')
print(df[["email", "domain"]])

               email       domain
0   test@example.com  example.com
1      user@yahoo.in     yahoo.in
2  coder@outlook.com  outlook.com
3     bademail@wrong          NaN
4    admin@gmail.com    gmail.com

In [31]:
df['clean'] = df['phone'].str.replace(r'\D','',regex = True)
df

               email             phone         name       domain         clean
0   test@example.com    +91-9876543210     John Doe  example.com  919876543210
1      user@yahoo.in     91 8765432109   Jane Smith     yahoo.in  918765432109
2  coder@outlook.com  (+91) 9998887776  Mike O'Neil  outlook.com  919998887776
3     bademail@wrong             12345   Anna-Marie          NaN         12345
4    admin@gmail.com        0987654321          Tom    gmail.com    0987654321