In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("data_cleaning_practice_large.csv",na_values = [""])
df.info()

In [ ]:
df['salary'] = pd.to_numeric(df['salary'])

In [ ]:
df.head(10)

In [ ]:
df.info()

# Missing Values Detect karna – isna() / isnull()

In [ ]:
df.isnull().sum()

## Missing Values Fill karna – fillna()

Common approaches: mean, median, mode, forward-fill, backward-fill.

In [ ]:
median_sal = df['salary'].median()
df['salary'] = df['salary'].fillna(median_sal)
df.head(15)

Alternate methods / shortcuts:

Ek line me:

df['Salary'].fillna(df['Salary'].median(), inplace=True)


Mode (most frequent value) se fill:

df['Dept'].fillna(df['Dept'].mode()[0], inplace=True)


Forward fill (pichle value se):

df['Salary'].fillna(method='ffill', inplace=True)


Backward fill (agle value se):

df['Salary'].fillna(method='bfill', inplace=True)

# Missing Values Drop karna – dropna()

In [ ]:
df.dropna(inplace=True)
df.head(10)

Column drop karna:

df.dropna(axis=1, inplace=True)


Only drop if all values NaN:

df.dropna(how='all', inplace=True)


Threshold (kam se kam values honi chahiye)

df.dropna(thresh=2, inplace=True)


(thresh=2 ka matlab row me kam se kam 2 non-NaN values honi chahiye)

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ravi", "Sita", "Aman", "Neha", "Rohit"],
    "Age": [25, np.nan, 30, 28, np.nan],
    "Salary": [50000, np.nan, 60000, np.nan, 75000],
    "Dept": ["IT", "HR", "Finance", "IT", "Finance"]
}

df = pd.DataFrame(data)
print(df)

    Name   Age   Salary     Dept
0   Ravi  25.0  50000.0       IT
1   Sita   NaN      NaN       HR
2   Aman  30.0  60000.0  Finance
3   Neha  28.0      NaN       IT
4  Rohit   NaN  75000.0  Finance

In [2]:
print(df['Salary'].dtype)

float64

In [3]:
print(df['Salary'].median())

60000.0

In [4]:
mean_sal = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_sal).round()
df

    Name   Age   Salary     Dept
0   Ravi  25.0  50000.0       IT
1   Sita  28.0      NaN       HR
2   Aman  30.0  60000.0  Finance
3   Neha  28.0      NaN       IT
4  Rohit  28.0  75000.0  Finance

In [5]:
df['Salary'].fillna(df['Salary'].median(),inplace = True)
df

C:\Users\gaura\AppData\Local\Temp\ipykernel_19760\1983299384.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].median(),inplace = True)

    Name   Age   Salary     Dept
0   Ravi  25.0  50000.0       IT
1   Sita  28.0  60000.0       HR
2   Aman  30.0  60000.0  Finance
3   Neha  28.0  60000.0       IT
4  Rohit  28.0  75000.0  Finance