In [1]:
import pandas as pd

data = {
    "customer_id": [1, 2, 3, 4, 5, 2, 6, 7, 8, 9, 10],
    "name": ["Ravi", "Sita", "Aman", "Neha", "Rohit", "Sita", "Anil", "Pooja", "Asha", "Karan", "Meena"],
    "email": ["ravi@x.com", "sita@x.com", "aman@x.com", "neha@x.com", "rohit@x.com",
              "sita@x.com", "anil@x.com", "pooja@x.com", "asha@x.com", "karan@x.com", "meena@x.com"],
    "salary": [50000, 60000, 55000, 62000, 70000, 60000, 58000, 65000, 59000, 61000, 1000000], # outlier salary
    "sales": [200, 300, 250, 400, 350, 300, 280, 500, 290, 310, 5000]  # outlier sales
}

df = pd.DataFrame(data)
print(df)

    customer_id   name        email   salary  sales
0             1   Ravi   ravi@x.com    50000    200
1             2   Sita   sita@x.com    60000    300
2             3   Aman   aman@x.com    55000    250
3             4   Neha   neha@x.com    62000    400
4             5  Rohit  rohit@x.com    70000    350
5             2   Sita   sita@x.com    60000    300
6             6   Anil   anil@x.com    58000    280
7             7  Pooja  pooja@x.com    65000    500
8             8   Asha   asha@x.com    59000    290
9             9  Karan  karan@x.com    61000    310
10           10  Meena  meena@x.com  1000000   5000

# Part 1: Duplicates

## Detect Duplicates

In [2]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
dtype: bool

## Count Duplicates

In [3]:
df.duplicated().sum()

np.int64(1)

## Remove Duplicates

In [ ]:
df_no_dup = df.drop_duplicates()
df_no_dup

# Part 2: Outlier Detection

## Method 1: IQR (Interquartile Range)

In [4]:
Q1 = df['sales'].quantile(0.25)
Q3 = df['sales'].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[(df['sales'] < lower_limit) | (df['sales'] > upper_limit)]
outliers

    customer_id   name        email   salary  sales
10           10  Meena  meena@x.com  1000000   5000

In [5]:
df

    customer_id   name        email   salary  sales
0             1   Ravi   ravi@x.com    50000    200
1             2   Sita   sita@x.com    60000    300
2             3   Aman   aman@x.com    55000    250
3             4   Neha   neha@x.com    62000    400
4             5  Rohit  rohit@x.com    70000    350
5             2   Sita   sita@x.com    60000    300
6             6   Anil   anil@x.com    58000    280
7             7  Pooja  pooja@x.com    65000    500
8             8   Asha   asha@x.com    59000    290
9             9  Karan  karan@x.com    61000    310
10           10  Meena  meena@x.com  1000000   5000

## Method 2: Z-Score (Standard Deviation method)

In [6]:
import numpy as np

mean_sales = df['sales'].mean()
std_sales = df['sales'].std()
df['z_score_sales'] = (df['sales'] - mean_sales) / std_sales
outliers_z = df[df['z_score_sales'].abs() > 3]
print(outliers_z)

    customer_id   name        email   salary  sales  z_score_sales
10           10  Meena  meena@x.com  1000000   5000       3.010407

# Part 3: Cleaning Outliers

### Remove Outliers

In [7]:
df_clean = df[(df['sales'] >= lower_limit) & (df['sales'] <= upper_limit)]
df_clean

   customer_id   name        email  salary  sales  z_score_sales
0            1   Ravi   ravi@x.com   50000    200      -0.384499
1            2   Sita   sita@x.com   60000    300      -0.313772
2            3   Aman   aman@x.com   55000    250      -0.349135
3            4   Neha   neha@x.com   62000    400      -0.243044
4            5  Rohit  rohit@x.com   70000    350      -0.278408
5            2   Sita   sita@x.com   60000    300      -0.313772
6            6   Anil   anil@x.com   58000    280      -0.327917
7            7  Pooja  pooja@x.com   65000    500      -0.172317
8            8   Asha   asha@x.com   59000    290      -0.320844
9            9  Karan  karan@x.com   61000    310      -0.306699

Tips & Tricks (Interview + Practice)

Duplicates:

Customer data me duplicates common hote hain → remove karna zaroori hai.

drop_duplicates(subset=["email"]) kaafi useful hota hai kyunki email unique hota hai.

Outliers:

Salary, Sales, Transaction Amount me hamesha check karna chahiye.

ML models (linear regression, clustering) outliers ke liye sensitive hote hain.

Business logic bhi consider karna padta hai → jaise 5000 sales ek galti ho sakti hai ya valid bhi.

In [8]:
#Duplicate customers ko remove karo (customer_id basis par).
df.duplicated().sum

<bound method Series.sum of 0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
dtype: bool>

In [9]:
df.drop_duplicates(subset = ["customer_id"],keep = "first")

    customer_id   name        email   salary  sales  z_score_sales
0             1   Ravi   ravi@x.com    50000    200      -0.384499
1             2   Sita   sita@x.com    60000    300      -0.313772
2             3   Aman   aman@x.com    55000    250      -0.349135
3             4   Neha   neha@x.com    62000    400      -0.243044
4             5  Rohit  rohit@x.com    70000    350      -0.278408
6             6   Anil   anil@x.com    58000    280      -0.327917
7             7  Pooja  pooja@x.com    65000    500      -0.172317
8             8   Asha   asha@x.com    59000    290      -0.320844
9             9  Karan  karan@x.com    61000    310      -0.306699
10           10  Meena  meena@x.com  1000000   5000       3.010407

In [10]:
df

    customer_id   name        email   salary  sales  z_score_sales
0             1   Ravi   ravi@x.com    50000    200      -0.384499
1             2   Sita   sita@x.com    60000    300      -0.313772
2             3   Aman   aman@x.com    55000    250      -0.349135
3             4   Neha   neha@x.com    62000    400      -0.243044
4             5  Rohit  rohit@x.com    70000    350      -0.278408
5             2   Sita   sita@x.com    60000    300      -0.313772
6             6   Anil   anil@x.com    58000    280      -0.327917
7             7  Pooja  pooja@x.com    65000    500      -0.172317
8             8   Asha   asha@x.com    59000    290      -0.320844
9             9  Karan  karan@x.com    61000    310      -0.306699
10           10  Meena  meena@x.com  1000000   5000       3.010407

In [11]:
import pandas as pd

data = {
    "customer_id": [1, 2, 3, 4, 5, 6],
    "name": ["Ravi", "Sita", "Sita", "Neha", "Ravi", "Aman"],
    "email": ["ravi@x.com", "sita@x.com", "sita@x.com", "neha@x.com", "ravi@x.com", "aman@x.com"],
    "sales": [200, 300, 300, 400, 200, 250]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
    customer_id  name       email  sales
0            1  Ravi  ravi@x.com    200
1            2  Sita  sita@x.com    300
2            3  Sita  sita@x.com    300
3            4  Neha  neha@x.com    400
4            5  Ravi  ravi@x.com    200
5            6  Aman  aman@x.com    250

In [12]:
df

   customer_id  name       email  sales
0            1  Ravi  ravi@x.com    200
1            2  Sita  sita@x.com    300
2            3  Sita  sita@x.com    300
3            4  Neha  neha@x.com    400
4            5  Ravi  ravi@x.com    200
5            6  Aman  aman@x.com    250

In [16]:
df_unq= df.drop_duplicates(subset = ["email"],keep = "last")
df_unq

   customer_id  name       email  sales
2            3  Sita  sita@x.com    300
3            4  Neha  neha@x.com    400
4            5  Ravi  ravi@x.com    200
5            6  Aman  aman@x.com    250

# real-world ETL style example

In [17]:
import pandas as pd

data = {
    "customer_id": [1, 2, 3, 4, 5, 6],
    "name": ["Ravi", "Sita", "Sita", "Neha", "Ravi", "Aman"],
    "email": ["ravi@x.com", "sita@x.com", "sita@x.com", "neha@x.com", "ravi@x.com", "aman@x.com"],
    "sales": [200, 300, 300, 400, 200, 250]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
    customer_id  name       email  sales
0            1  Ravi  ravi@x.com    200
1            2  Sita  sita@x.com    300
2            3  Sita  sita@x.com    300
3            4  Neha  neha@x.com    400
4            5  Ravi  ravi@x.com    200
5            6  Aman  aman@x.com    250

In [19]:
df_clean = df.groupby("email", as_index=False).agg({
    "name": "first",        # pehla naam rakha (ya mode bhi le sakte ho)
    "sales": "sum"          # sales ko aggregate (sum) kar diya
})
print("\nDeduplicated & Consolidated Table:\n", df_clean)

# Duplicate emails hat gaye.

# Har email ke liye ek hi row rakh li gayi.

# Sales column ko aggregate (sum) karke consolidate kar diya.

# Ravi ke 2 transactions (200 + 200 = 400)

# Sita ke 2 transactions (300 + 300 = 600)

Deduplicated & Consolidated Table:
         email  name  sales
0  aman@x.com  Aman    250
1  neha@x.com  Neha    400
2  ravi@x.com  Ravi    400
3  sita@x.com  Sita    600