In [1]:
import pandas as pd

data = {
    "customer_id": [1, 2, 3, 4, 5, 6],
    "name": ["Ravi Kumar", "Sita Devi", "Aman Singh", "Neha", "Rohit123", "Pooja Sharma"],
    "email": ["ravi@gmail.com", "sita@yahoo.com", "aman@company.com", 
              "neha_gmail.com", "rohit@outlook.com", "pooja@@gmail.com"],
    "phone": ["+91-9876543210", "98765 43211", "123-456-7890", "99999-88888", "0000000000", "91-9898989898"],
    "address": ["Delhi, India", "Mumbai", "Noida, UP", "Bangalore, KA", "Pune", "Hyderabad, TS"]
}

df = pd.DataFrame(data)
print(df)

   customer_id          name              email           phone        address
0            1    Ravi Kumar     ravi@gmail.com  +91-9876543210   Delhi, India
1            2     Sita Devi     sita@yahoo.com     98765 43211         Mumbai
2            3    Aman Singh   aman@company.com    123-456-7890      Noida, UP
3            4          Neha     neha_gmail.com     99999-88888  Bangalore, KA
4            5      Rohit123  rohit@outlook.com      0000000000           Pune
5            6  Pooja Sharma   pooja@@gmail.com   91-9898989898  Hyderabad, TS

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  6 non-null      int64
 1   name         6 non-null      object
 2   email        6 non-null      object
 3   phone        6 non-null      object
 4   address      6 non-null      object
dtypes: int64(1), object(4)
memory usage: 372.0+ bytes

# 1. .str.contains()

#### Example 1: Emails me "gmail" hai?

In [3]:
df["is_gmail"] = df["email"].str.contains("gmail",na = False)
df["is_gmail"]

0     True
1    False
2    False
3     True
4    False
5     True
Name: is_gmail, dtype: bool

### Example 2: Phone number India ka (+91) hai?

In [4]:
df["is_ind_num"] = df["phone"].str.contains(r'^\+91',regex = True)
df["is_ind_num"].sum()

np.int64(1)

# 2. .str.replace()
Strings me unwanted characters ya patterns ko replace karna.

In [5]:
#Example 1: Phone numbers clean karna (digits only)
df['clean_phone'] = df['phone'].str.replace(r'\D', '', regex=True)
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898

In [6]:
#Example 2: Names me numbers hatao
df["clean_name"] = df["name"].str.replace(r'\d+','',regex = True)

df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma

# 3 Regex with .str.extract()

In [13]:
#Example 1: Email se domain nikalna
df['domain'] =  df['email'].str.extract(r'@(\w+\.\w+)')
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email,provider,standard_phone
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True,gmail.com,9876543210
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True,yahoo.com,9876543211
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True,company.com,1234567890
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False,NaN,9999988888
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True,outlook.com,0000000000
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True,gmail.com,9898989898

#### Lowercase / Uppercase

In [14]:
df['name_lower'] = df['name'].str.lower()
df['name_upper'] = df['name'].str.upper()
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email,provider,standard_phone
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True,gmail.com,9876543210
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True,yahoo.com,9876543211
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True,company.com,1234567890
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False,NaN,9999988888
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True,outlook.com,0000000000
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True,gmail.com,9898989898

#### Substring split (e.g., first name, last name)

In [9]:
df[['first_name', 'last_name']] = df['name'].str.split(" ", n=1, expand=True)# expand = True ka matlab hai ki result alag alag column me ayenge,n=1 matlab ek hi split hoga wo bhi pahle space ke bad
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma

In [10]:
df['valid_email'] = df['email'].str.contains(r'@.+\..+', regex=True)
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True

In [11]:
df['provider'] = df["email"].str.extract(r'@(\w+\.\w+)')
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email,provider
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True,gmail.com
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True,yahoo.com
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True,company.com
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False,NaN
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True,outlook.com
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True,gmail.com

In [15]:
#Phone numbers ko standardize karna (sirf 10 digits chhodo).
df["clean_phone"] = df['phone'].str.replace(r'\D', '', regex=True)
df["standard_phone"] = df["clean_phone"].str[-10:]
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email,provider,standard_phone
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True,gmail.com,9876543210
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True,yahoo.com,9876543211
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True,company.com,1234567890
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False,NaN,9999988888
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True,outlook.com,0000000000
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True,gmail.com,9898989898

In [16]:
df = df.drop(columns = ["provider"])
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email,standard_phone
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True,9876543210
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True,9876543211
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True,1234567890
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False,9999988888
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True,0000000000
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True,9898989898

In [17]:
df

,customer_id,name,email,phone,address,is_gmail,is_ind_num,clean_phone,clean_name,domain,name_lower,name_upper,first_name,last_name,valid_email,standard_phone
0,1,Ravi Kumar,ravi@gmail.com,+91-9876543210,"Delhi, India",True,True,919876543210,Ravi Kumar,gmail.com,ravi kumar,RAVI KUMAR,Ravi,Kumar,True,9876543210
1,2,Sita Devi,sita@yahoo.com,98765 43211,Mumbai,False,False,9876543211,Sita Devi,yahoo.com,sita devi,SITA DEVI,Sita,Devi,True,9876543211
2,3,Aman Singh,aman@company.com,123-456-7890,"Noida, UP",False,False,1234567890,Aman Singh,company.com,aman singh,AMAN SINGH,Aman,Singh,True,1234567890
3,4,Neha,neha_gmail.com,99999-88888,"Bangalore, KA",True,False,9999988888,Neha,NaN,neha,NEHA,Neha,None,False,9999988888
4,5,Rohit123,rohit@outlook.com,0000000000,Pune,False,False,0000000000,Rohit,outlook.com,rohit123,ROHIT123,Rohit123,None,True,0000000000
5,6,Pooja Sharma,pooja@@gmail.com,91-9898989898,"Hyderabad, TS",True,False,919898989898,Pooja Sharma,gmail.com,pooja sharma,POOJA SHARMA,Pooja,Sharma,True,9898989898