In [14]:
import pandas as pd

data = {
    "Customer ID": [1, 2, 3],
    "Full Name": ["Ravi Kumar", "Sita Devi", "Aman Verma"],
    "TotalSales(₹)": [2000, 3000, 2500],
    "Join Date": ["2023-01-01", "2023-02-15", "2023-03-20"]
}

df = pd.DataFrame(data)
print("Original DF:\n", df)

Original DF:
    Customer ID   Full Name  TotalSales(₹)   Join Date
0            1  Ravi Kumar           2000  2023-01-01
1            2   Sita Devi           3000  2023-02-15
2            3  Aman Verma           2500  2023-03-20

# Column Renaming
### a) Rename single column

In [15]:
df.rename(columns={'Customer ID': 'customer_id'},inplace=True)

In [16]:
df.rename(columns={"Full Name": "full_name","TotalSales(₹)": "total_sales","Join Date": "join_date"},inplace=True)
df

   customer_id   full_name  total_sales   join_date
0            1  Ravi Kumar         2000  2023-01-01
1            2   Sita Devi         3000  2023-02-15
2            3  Aman Verma         2500  2023-03-20

### c) Rename using str methods (shortcuts)

In [17]:
# All column names to lowercase
df.columns = df.columns.str.lower()
# Replace spaces with underscore
df.columns = df.columns.str.replace(" ", "_")
# Remove special characters (like ₹, (), etc.)
df.columns = df.columns.str.replace(r'[^a-zA-Z0-9_]', '', regex=True)

In [18]:
df

   customer_id   full_name  total_sales   join_date
0            1  Ravi Kumar         2000  2023-01-01
1            2   Sita Devi         3000  2023-02-15
2            3  Aman Verma         2500  2023-03-20

# 2. Column Reordering
### a) By providing list of column names

In [19]:
df= df[["customer_id", "full_name", "join_date", "total_sales"]]
df

   customer_id   full_name   join_date  total_sales
0            1  Ravi Kumar  2023-01-01         2000
1            2   Sita Devi  2023-02-15         3000
2            3  Aman Verma  2023-03-20         2500

### b) pop() trick (ek column ko nikalke end me ya kahin aur dalna)

In [20]:
sales = df.pop("total_sales")   # remove
df["total_sales"] = sales       # add at the end
df

   customer_id   full_name   join_date  total_sales
0            1  Ravi Kumar  2023-01-01         2000
1            2   Sita Devi  2023-02-15         3000
2            3  Aman Verma  2023-03-20         2500

c) Move first column to last (generic)
cols = df.columns.tolist()
df = df[cols[1:] + [cols[0]]]

# Function: Convert to Snake Case

In [25]:
import re
import pandas as pd

def to_snake_case(df):
    """
    Convert all dataframe column names to snake_case
    and remove special characters.
    """
    new_cols = []
    for col in df.columns:
        # Lowercase
        col = col.lower()
        # Replace spaces and hyphens with underscore
        col = re.sub(r'[\s\-]+', '_', col)
        # Remove special characters except underscore
        col = re.sub(r'[^a-z0-9_]', '', col)
        # Remove leading/trailing underscores
        col = col.strip('_')
        new_cols.append(col)
    df.columns = new_cols
    return df

In [22]:
data = {
    "Customer ID": [1, 2, 3],
    "Full Name": ["Ravi Kumar", "Sita Devi", "Aman Verma"],
    "TotalSales(₹)": [2000, 3000, 2500],
    "Join-Date": ["2023-01-01", "2023-02-15", "2023-03-20"]
}

In [23]:
df = pd.DataFrame(data)
print("Original columns:", df.columns.tolist())

Original columns: ['Customer ID', 'Full Name', 'TotalSales(₹)', 'Join-Date']

In [24]:
df = to_snake_case(df)
print("Snake_case columns:", df.columns.tolist())

Snake_case columns: ['customer_id', 'full_name', 'totalsales', 'join_date']

In [29]:
df.columns

Index(['customer_id', 'full_name', 'totalsales', 'join_date'], dtype='object')