In [5]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('messy_customers.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CustomerID   205 non-null    object
 1   Name         205 non-null    object
 2   Age          202 non-null    float64
 3   City         205 non-null    object
 4   Total_Sales  205 non-null    float64
 5   Email        205 non-null    object
 6   JoinDate     148 non-null    object
dtypes: float64(2), object(5)
memory usage: 11.3+ KB

## Load & Initial Exploration

In [27]:
df.describe()

              age   total_sales                       joindate
count  202.000000    205.000000                            148
mean    38.945545  25653.882293  2022-04-18 21:43:47.027026944
min     18.000000   1019.450000            2021-07-20 00:00:00
25%     29.000000  12466.110000            2021-07-20 00:00:00
50%     39.000000  26274.970000            2022-01-15 00:00:00
75%     50.000000  36763.070000            2023-03-05 00:00:00
max     59.000000  49991.290000            2023-03-05 00:00:00
std     12.168061  14548.490055                            NaN

In [18]:
df.head(5)

,customerid,name,age,city,total_sales,email,joindate
0,CUST1000,Amit,50.0,Chennai,48835.56,amit0@outlook.com,NaN
1,CUST1001,Amit,46.0,Bangalore,40933.26,amit1@hotmail.com,NaN
2,CUST1002,Meera,43.0,Delhi,28920.61,meera2@hotmail.com,2022-01-15
3,CUST1003,Vikas,NaN,Delhi,35732.54,vikas3@gmail.com,NaN
4,CUST1004,Priya,39.0,Chennai,7775.87,priya4@hotmail.com,2022-01-15

## Check Column Names & Rename

In [28]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['customerid', 'name', 'age', 'city', 'total_sales', 'email',
       'joindate'],
      dtype='object')

In [29]:
df.head(4)

,customerid,name,age,city,total_sales,email,joindate
0,CUST1000,Amit,50.0,Chennai,48835.56,amit0@outlook.com,NaT
1,CUST1001,Amit,46.0,Bangalore,40933.26,amit1@hotmail.com,NaT
2,CUST1002,Meera,43.0,Delhi,28920.61,meera2@hotmail.com,2022-01-15
3,CUST1003,Vikas,NaN,Delhi,35732.54,vikas3@gmail.com,NaT

In [30]:
df['joindate'] = pd.to_datetime(df['joindate'],errors = 'coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customerid   205 non-null    object
 1   name         205 non-null    object
 2   age          202 non-null    float64
 3   city         205 non-null    object
 4   total_sales  205 non-null    float64
 5   email        205 non-null    object
 6   joindate     148 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 11.3+ KB

In [24]:
df[['city','name']] = df[['city','name']].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customerid   205 non-null    object
 1   name         205 non-null    object
 2   age          202 non-null    float64
 3   city         205 non-null    object
 4   total_sales  205 non-null    float64
 5   email        205 non-null    object
 6   joindate     148 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 11.3+ KB

# Missing Data Handling

In [32]:
df.isna().sum()

customerid      0
name            0
age             3
city            0
total_sales     0
email           0
joindate       57
dtype: int64

In [48]:
df['joindate'] = df['joindate'].ffill()
df['age'] = df['age'].ffill()
df.isna().sum()

customerid     0
name           0
age            0
city           0
total_sales    0
email          0
joindate       0
dtype: int64

In [41]:
df['joindate'] = df['joindate'].bfill()
df.isna().sum()

customerid     0
name           0
age            0
city           0
total_sales    0
email          0
joindate       0
dtype: int64

# Duplicate Records Check

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df = df.drop_duplicates()

# Outlier Detection

In [53]:
Q1 = df['total_sales'].quantile(0.25)
Q3 = df['total_sales'].quantile(0.75)
IQR = Q3 - Q1
df = df[(df['total_sales'] >= Q1-1.5*IQR) & (df['total_sales'] <= Q3+1.5*IQR)]
df_clean = df[(df['total_sales'] >= Q1 - 1.5 * IQR) & (df['total_sales'] <= Q3+1.5*IQR) ]
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customerid   200 non-null    object
 1   name         200 non-null    object
 2   age          200 non-null    float64
 3   city         200 non-null    object
 4   total_sales  200 non-null    float64
 5   email        200 non-null    object
 6   joindate     200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 12.5+ KB

# String Cleaning & Regex

In [58]:
df['email'].sample(20)

107        amit107@gmail.com
141      ravi141@hotmail.com
191     priya191@hotmail.com
131       raj131@hotmail.com
97        anjali97@gmail.com
104    anjali104@outlook.com
8          ravi8@outlook.com
112       vikas112@gmail.com
77           raj77@gmail.com
87        ravi87@hotmail.com
166       karan166@gmail.com
118       karan118@gmail.com
71        amit71@outlook.com
49          ravi49@gmail.com
72        amit72@outlook.com
65          amit65@gmail.com
160        amit160@gmail.com
130       meera130@gmail.com
66          ravi66@yahoo.com
62         raj62@outlook.com
Name: email, dtype: object

In [59]:
df['email_domain'] = df['email'].str.extract(r'@(\w+\.\w+)')
df.head(10)

,customerid,name,age,city,total_sales,email,joindate,email_domain
0,CUST1000,Amit,50.0,Chennai,48835.56,amit0@outlook.com,2022-01-15,outlook.com
1,CUST1001,Amit,46.0,Bangalore,40933.26,amit1@hotmail.com,2022-01-15,hotmail.com
2,CUST1002,Meera,43.0,Delhi,28920.61,meera2@hotmail.com,2022-01-15,hotmail.com
3,CUST1003,Vikas,43.0,Delhi,35732.54,vikas3@gmail.com,2022-01-15,gmail.com
4,CUST1004,Priya,39.0,Chennai,7775.87,priya4@hotmail.com,2022-01-15,hotmail.com
5,CUST1005,Anjali,58.0,Mumbai,36556.58,anjali5@outlook.com,2021-07-20,outlook.com
6,CUST1006,Raj,23.0,Mumbai,44846.29,raj6@yahoo.com,2021-07-20,yahoo.com
7,CUST1007,Karan,21.0,Chennai,21771.51,karan7@gmail.com,2021-07-20,gmail.com
8,CUST1008,Ravi,47.0,Bangalore,11056.02,ravi8@outlook.com,2021-07-20,outlook.com
9,CUST1009,Meera,26.0,Chennai,33272.18,meera9@gmail.com,2021-07-20,gmail.com

In [61]:
df['join_month'] = df['joindate'].dt.month_name()
df.head(10)

,customerid,name,age,city,total_sales,email,joindate,email_domain,join_month
0,CUST1000,Amit,50.0,Chennai,48835.56,amit0@outlook.com,2022-01-15,outlook.com,January
1,CUST1001,Amit,46.0,Bangalore,40933.26,amit1@hotmail.com,2022-01-15,hotmail.com,January
2,CUST1002,Meera,43.0,Delhi,28920.61,meera2@hotmail.com,2022-01-15,hotmail.com,January
3,CUST1003,Vikas,43.0,Delhi,35732.54,vikas3@gmail.com,2022-01-15,gmail.com,January
4,CUST1004,Priya,39.0,Chennai,7775.87,priya4@hotmail.com,2022-01-15,hotmail.com,January
5,CUST1005,Anjali,58.0,Mumbai,36556.58,anjali5@outlook.com,2021-07-20,outlook.com,July
6,CUST1006,Raj,23.0,Mumbai,44846.29,raj6@yahoo.com,2021-07-20,yahoo.com,July
7,CUST1007,Karan,21.0,Chennai,21771.51,karan7@gmail.com,2021-07-20,gmail.com,July
8,CUST1008,Ravi,47.0,Bangalore,11056.02,ravi8@outlook.com,2021-07-20,outlook.com,July
9,CUST1009,Meera,26.0,Chennai,33272.18,meera9@gmail.com,2021-07-20,gmail.com,July

# Filtering & Boolean Indexing

In [66]:
df[(df['age'] > 30) & (df['city'] == 'Delhi') & (df['join_month'] == 'January')]

,customerid,name,age,city,total_sales,email,joindate,email_domain,join_month
2,CUST1002,Meera,43.0,Delhi,28920.61,meera2@hotmail.com,2022-01-15,hotmail.com,January
3,CUST1003,Vikas,43.0,Delhi,35732.54,vikas3@gmail.com,2022-01-15,gmail.com,January
74,CUST1074,Priya,32.0,Delhi,3808.57,priya74@yahoo.com,2022-01-15,yahoo.com,January
80,CUST1080,Priya,41.0,Delhi,17154.50,priya80@hotmail.com,2022-01-15,hotmail.com,January
108,CUST1108,Neha,42.0,Delhi,6692.78,neha108@gmail.com,2022-01-15,gmail.com,January
148,CUST1148,Neha,50.0,Delhi,4877.98,neha148@yahoo.com,2022-01-15,yahoo.com,January
163,CUST1163,Raj,40.0,Delhi,46283.08,raj163@gmail.com,2022-01-15,gmail.com,January