In [1]:
import pandas as pd
df = pd.read_csv('employees.csv')

df.duplicated().sum()

# df[df.duplicated(keep = False)] # keep = False -> show all the duplicate rows,by default it is 'first' 
                                # which shows only the first occurrence of the duplicate rows.

np.int64(20)

In [ ]:
# df_clean =df.drop_duplicates(keep = 'last')
# df_clean
# df_clean =df.drop_duplicates(keep = False) # drop all the duplicate rows
# df_clean

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
6,1007,Karan Mishra,35.0,Male,Engineering,Senior,82266.0,Delhi,12-02-2024,12,2.8,karan.mishra@company.com
7,1008,Vivaan Chauhan,27.0,Female,HR,Associate,65792.0,Ahmedabad,25-10-2022,3,3.5,vivaan.chauhan@company.com
8,1009,Nikhil Patel,24.0,Female,Marketing,Senior,85452.0,Jaipur,14-01-2017,1,4.2,nikhil.patel@company.com
9,1010,Vivaan Bansal,37.0,Male,Support,Senior,94511.0,Pune,25-01-2024,17,5.0,vivaan.bansal@company.com
10,1011,Rohan Sharma,28.0,Female,Engineering,Lead,95758.0,Chennai,11-04-2021,7,4.0,rohan.sharma@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-2019,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-2021,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-2018,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-2023,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-2019,16,3.0,rakesh.chopra@company.com

In [6]:
df[df.duplicated(keep = False)]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-2024,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-2016,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-2017,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-2015,30,NaN,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-2021,24,3.6,geeta.nair@company.com
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-2019,29,3.2,rahul.gupta@company.com
480,1481,Aadhya Yadav,26.0,Female,Operations,Junior,30192.0,Kolkata,20-10-2021,4,3.3,aadhya.yadav@company.com
481,1482,Deepak Reddy,32.0,Male,Finance,Manager,128160.0,Hyderabad,06-11-2018,8,2.8,deepak.reddy@company.com
482,1483,Shreya Yadav,33.0,Male,PRODUCT,Lead,88645.0,Ahmedabad,22-11-2020,13,3.7,shreya.yadav@company.com
483,1484,Anvi Shah,31.0,Male,Product,Lead,97816.0,Bangalore,10-07-2023,11,3.2,anvi.shah@company.com
484,1485,Varun Yadav,29.0,Male,Operations,Intern,21314.0,Pune,04-10-2018,5,3.7,varun.yadav@company.com
485,1486,Anvi Pillai,45.0,Male,Product,Associate,69826.0,Jaipur,02-04-2024,25,4.3,anvi.pillai@company.com
486,1487,Vikram Singh,49.0,Female,Finance,Associate,63172.0,Mumbai,27-02-2018,26,2.6,vikram.singh@company.com
487,1488,Ishaan Gupta,57.0,Male,Finance,Associate,52374.0,Mumbai,15-10-2015,35,4.3,ishaan.gupta@company.com
488,1489,Priya Chopra,42.0,Female,Finance,Junior,33700.0,Ahmedabad,24-10-2016,22,2.9,priya.chopra@company.com
489,1490,Meera Chopra,29.0,Female,Operations,Director,160655.0,Bangalore,02-10-2025,5,5.0,meera.chopra@company.com
490,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-2025,9,4.8,ayaan.joshi@company.com
491,1492,Gaurav Rao,36.0,Male,Product,Associate,54359.0,Mumbai,02-04-2018,16,NaN,gaurav.rao@company.com
492,1493,Sai Kulkarni,39.0,Female,Product,Associate,48893.0,Chennai,13-08-2021,19,2.7,sai.kulkarni@company.com
493,1494,Suresh Verma,41.0,Female,Engineering,Senior,71811.0,Pune,10-11-2017,20,2.6,suresh.verma@company.com
505,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-2024,10,3.5,kriti.saxena@company.com
506,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-2016,15,NaN,aadhya.nair@company.com
507,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-2017,34,4.3,bhavna.saxena@company.com
508,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-2015,30,NaN,rohan.shah@company.com
509,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-2021,24,3.6,geeta.nair@company.com
510,1006,Rahul Gupta,51.0,Male,Product,VP,209477.0,Ahmedabad,26-09-2019,29,3.2,rahul.gupta@company.com
511,1481,Aadhya Yadav,26.0,Female,Operations,Junior,30192.0,Kolkata,20-10-2021,4,3.3,aadhya.yadav@company.com
512,1482,Deepak Reddy,32.0,Male,Finance,Manager,128160.0,Hyderabad,06-11-2018,8,2.8,deepak.reddy@company.com
513,1483,Shreya Yadav,33.0,Male,PRODUCT,Lead,88645.0,Ahmedabad,22-11-2020,13,3.7,shreya.yadav@company.com
514,1484,Anvi Shah,31.0,Male,Product,Lead,97816.0,Bangalore,10-07-2023,11,3.2,anvi.shah@company.com
515,1485,Varun Yadav,29.0,Male,Operations,Intern,21314.0,Pune,04-10-2018,5,3.7,varun.yadav@company.com
516,1486,Anvi Pillai,45.0,Male,Product,Associate,69826.0,Jaipur,02-04-2024,25,4.3,anvi.pillai@company.com
517,1487,Vikram Singh,49.0,Female,Finance,Associate,63172.0,Mumbai,27-02-2018,26,2.6,vikram.singh@company.com
518,1488,Ishaan Gupta,57.0,Male,Finance,Associate,52374.0,Mumbai,15-10-2015,35,4.3,ishaan.gupta@company.com
519,1489,Priya Chopra,42.0,Female,Finance,Junior,33700.0,Ahmedabad,24-10-2016,22,2.9,priya.chopra@company.com
520,1490,Meera Chopra,29.0,Female,Operations,Director,160655.0,Bangalore,02-10-2025,5,5.0,meera.chopra@company.com
521,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-2025,9,4.8,ayaan.joshi@company.com
522,1492,Gaurav Rao,36.0,Male,Product,Associate,54359.0,Mumbai,02-04-2018,16,NaN,gaurav.rao@company.com
523,1493,Sai Kulkarni,39.0,Female,Product,Associate,48893.0,Chennai,13-08-2021,19,2.7,sai.kulkarni@company.com
524,1494,Suresh Verma,41.0,Female,Engineering,Senior,71811.0,Pune,10-11-2017,20,2.6,suresh.verma@company.com

In [7]:
df_clean = df.drop_duplicates(keep = 'first')
df_clean

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-2024,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-2016,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-2017,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-2015,30,NaN,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-2021,24,3.6,geeta.nair@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135.0,kolkata,09-10-2019,13,3.5,pallavi.chauhan@company.com
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-2021,24,3.6,geeta.nair@company.com
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060.0,Chennai,16-03-2018,5,3.3,aditya.mishra@company.com
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299.0,Mumbai,05-11-2023,19,4.4,shweta.pillai@company.com
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886.0,Surat,20-08-2019,16,3.0,rakesh.chopra@company.com

In [ ]:
#check if there are employees with same name and email

df[df.duplicated(subset = ['name', 'email'], keep = False)]

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,email
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646.0,Delhi,25-04-2024,10,3.5,kriti.saxena@company.com
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835.0,Pune,24-05-2016,15,NaN,aadhya.nair@company.com
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051.0,Pune,28-06-2017,34,4.3,bhavna.saxena@company.com
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798.0,Mumbai,11-03-2015,30,NaN,rohan.shah@company.com
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113.0,Kolkata,04-03-2021,24,3.6,geeta.nair@company.com
...,...,...,...,...,...,...,...,...,...,...,...,...
520,1490,Meera Chopra,29.0,Female,Operations,Director,160655.0,Bangalore,02-10-2025,5,5.0,meera.chopra@company.com
521,1491,Ayaan Joshi,30.0,Male,Engineering,Senior,80129.0,Chennai,30-09-2025,9,4.8,ayaan.joshi@company.com
522,1492,Gaurav Rao,36.0,Male,Product,Associate,54359.0,Mumbai,02-04-2018,16,NaN,gaurav.rao@company.com
523,1493,Sai Kulkarni,39.0,Female,Product,Associate,48893.0,Chennai,13-08-2021,19,2.7,sai.kulkarni@company.com
524,1494,Suresh Verma,41.0,Female,Engineering,Senior,71811.0,Pune,10-11-2017,20,2.6,suresh.verma@company.com