In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("employees.csv")
df.isnull().sum()

emp_id               0
name                 0
age                 15
gender               0
department           8
designation          0
salary              20
city                10
join_date            0
experience_years     0
rating              25
email                0
dtype: int64

In [15]:
df['salary'] = df['salary'].fillna(0).astype(int)
df['annual_salary'] = df['salary'] * 12
df[['salary','annual_salary']]
df['tax'] = df['annual_salary'] * 0.3
df['inhand_salary'] = df['annual_salary'] - df['tax']
df[['annual_salary','tax','inhand_salary']]

     annual_salary       tax  inhand_salary
0          1603752  481125.6      1122626.4
1           982020  294606.0       687414.0
2           504612  151383.6       353228.4
3           873576  262072.8       611503.2
4          1093356  328006.8       765349.2
..             ...       ...            ...
500         661620  198486.0       463134.0
501        1093356  328006.8       765349.2
502         660720  198216.0       462504.0
503        1059588  317876.4       741711.6
504        1654632  496389.6      1158242.4

[505 rows x 3 columns]

In [16]:
import numpy as np
df['is_senior'] = np.where(df['experience_years']>=20,'Yes','No')
conditions = [
    df['salary'] < 100000,
    (df['salary'] >= 100000) & (df['salary'] < 250000),
    df['salary'] >= 250000
]
choices = ['Low','Medium','High']
df['salary_level'] = np.select(conditions,choices,default='Unknown')
df[['salary','salary_level','is_senior']]

     salary salary_level is_senior
0    133646       Medium        No
1     81835          Low        No
2     42051          Low       Yes
3     72798          Low       Yes
4     91113          Low       Yes
..      ...          ...       ...
500   55135          Low        No
501   91113          Low       Yes
502   55060          Low        No
503   88299          Low        No
504  137886       Medium        No

[505 rows x 3 columns]

In [17]:
df['salary'].mean()

np.float64(82352.18415841584)

In [18]:
df.columns

Index(['emp_id', 'name', 'age', 'gender', 'department', 'designation',
       'salary', 'city', 'join_date', 'experience_years', 'rating', 'email',
       'annual_salary', 'tax', 'inhand_salary', 'is_senior', 'salary_level'],
      dtype='object')

In [19]:
#removing columns
df = df.drop(columns = ['email'])
df

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,annual_salary,tax,inhand_salary,is_senior,salary_level
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646,Delhi,25-04-24,10,3.5,1603752,481125.6,1122626.4,No,Medium
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835,Pune,24-05-16,15,NaN,982020,294606.0,687414.0,No,Low
2,1003,Bhavna Saxena,56.0,Male,Engineering,Intern,42051,Pune,28-06-17,34,4.3,504612,151383.6,353228.4,Yes,Low
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798,Mumbai,11-03-15,30,NaN,873576,262072.8,611503.2,Yes,Low
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,328006.8,765349.2,Yes,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135,kolkata,09-10-19,13,3.5,661620,198486.0,463134.0,No,Low
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,328006.8,765349.2,Yes,Low
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060,Chennai,16-03-18,5,3.3,660720,198216.0,462504.0,No,Low
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299,Mumbai,05-11-23,19,4.4,1059588,317876.4,741711.6,No,Low
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886,Surat,20-08-19,16,3.0,1654632,496389.6,1158242.4,No,Medium

In [20]:
#sari ki sari rows nikal do jisme salary 50k se kam hai
df = df[df['salary'] > 50000]
df

#sirf wo rows jisme salary 50k se upaar hai

,emp_id,name,age,gender,department,designation,salary,city,join_date,experience_years,rating,annual_salary,tax,inhand_salary,is_senior,salary_level
0,1001,Kriti Saxena,33.0,Male,Engineering,Manager,133646,Delhi,25-04-24,10,3.5,1603752,481125.6,1122626.4,No,Medium
1,1002,Aadhya Nair,39.0,Female,Engineering,Senior,81835,Pune,24-05-16,15,NaN,982020,294606.0,687414.0,No,Low
3,1004,Rohan Shah,51.0,Male,Sales,Associate,72798,Mumbai,11-03-15,30,NaN,873576,262072.8,611503.2,Yes,Low
4,1005,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,328006.8,765349.2,Yes,Low
5,1006,Rahul Gupta,51.0,Male,Product,VP,209477,Ahmedabad,26-09-19,29,3.2,2513724,754117.2,1759606.8,Yes,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135,kolkata,09-10-19,13,3.5,661620,198486.0,463134.0,No,Low
501,1502,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,328006.8,765349.2,Yes,Low
502,1503,Aditya Mishra,27.0,Female,Engineering,Junior,55060,Chennai,16-03-18,5,3.3,660720,198216.0,462504.0,No,Low
503,1504,Shweta Pillai,41.0,Female,Sales,Senior,88299,Mumbai,05-11-23,19,4.4,1059588,317876.4,741711.6,No,Low
504,1505,Rakesh Chopra,37.0,Male,Support,Manager,137886,Surat,20-08-19,16,3.0,1654632,496389.6,1158242.4,No,Medium

In [21]:
df.insert(2,'full_name',df['name'])
df

,emp_id,name,full_name,age,gender,department,designation,salary,city,join_date,experience_years,rating,annual_salary,tax,inhand_salary,is_senior,salary_level
0,1001,Kriti Saxena,Kriti Saxena,33.0,Male,Engineering,Manager,133646,Delhi,25-04-24,10,3.5,1603752,481125.6,1122626.4,No,Medium
1,1002,Aadhya Nair,Aadhya Nair,39.0,Female,Engineering,Senior,81835,Pune,24-05-16,15,NaN,982020,294606.0,687414.0,No,Low
3,1004,Rohan Shah,Rohan Shah,51.0,Male,Sales,Associate,72798,Mumbai,11-03-15,30,NaN,873576,262072.8,611503.2,Yes,Low
4,1005,Geeta Nair,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,328006.8,765349.2,Yes,Low
5,1006,Rahul Gupta,Rahul Gupta,51.0,Male,Product,VP,209477,Ahmedabad,26-09-19,29,3.2,2513724,754117.2,1759606.8,Yes,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,1501,Pallavi Chauhan,Pallavi Chauhan,34.0,Female,Engineering,Junior,55135,kolkata,09-10-19,13,3.5,661620,198486.0,463134.0,No,Low
501,1502,Geeta Nair,Geeta Nair,45.0,Female,Engineering,Senior,91113,Kolkata,04-03-21,24,3.6,1093356,328006.8,765349.2,Yes,Low
502,1503,Aditya Mishra,Aditya Mishra,27.0,Female,Engineering,Junior,55060,Chennai,16-03-18,5,3.3,660720,198216.0,462504.0,No,Low
503,1504,Shweta Pillai,Shweta Pillai,41.0,Female,Sales,Senior,88299,Mumbai,05-11-23,19,4.4,1059588,317876.4,741711.6,No,Low
504,1505,Rakesh Chopra,Rakesh Chopra,37.0,Male,Support,Manager,137886,Surat,20-08-19,16,3.0,1654632,496389.6,1158242.4,No,Medium