In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("employees.csv")
df['salary']

0      133646.0
1       81835.0
2       42051.0
3       72798.0
4       91113.0
         ...
500     55135.0
501     91113.0
502     55060.0
503     88299.0
504    137886.0
Name: salary, Length: 505, dtype: float64

In [6]:
# apply a custom function
def select_category(salary):
    if salary >= 120000:
        return 'High'
    elif salary >= 80000:
        return 'Medium'
    else:
        return 'Low'
    
def summary(row):
    return f"{row['name']} has a salary of {row['salary']}"


df['salary_category'] = df['salary'].apply(select_category)
df['summary'] = df.apply(summary, axis=1)

df['last_name'] = df['name'].apply(lambda name: name.split()[-1])
df[["salary_category", "salary", "name", "last_name", "summary"]]

,salary_category,salary,name,last_name,summary
0,High,133646.0,Kriti Saxena,Saxena,Kriti Saxena has a salary of 133646.0
1,Medium,81835.0,Aadhya Nair,Nair,Aadhya Nair has a salary of 81835.0
2,Low,42051.0,Bhavna Saxena,Saxena,Bhavna Saxena has a salary of 42051.0
3,Low,72798.0,Rohan Shah,Shah,Rohan Shah has a salary of 72798.0
4,Medium,91113.0,Geeta Nair,Nair,Geeta Nair has a salary of 91113.0
...,...,...,...,...,...
500,Low,55135.0,Pallavi Chauhan,Chauhan,Pallavi Chauhan has a salary of 55135.0
501,Medium,91113.0,Geeta Nair,Nair,Geeta Nair has a salary of 91113.0
502,Low,55060.0,Aditya Mishra,Mishra,Aditya Mishra has a salary of 55060.0
503,Medium,88299.0,Shweta Pillai,Pillai,Shweta Pillai has a salary of 88299.0
504,High,137886.0,Rakesh Chopra,Chopra,Rakesh Chopra has a salary of 137886.0

In [8]:
df['bonus_elegibile'] = df['rating'].apply(lambda rating: 'Yes' if rating >= 4 else 'No')
df[['rating','bonus_elegibile']]

     rating bonus_elegibile
0       3.5              No
1       NaN              No
2       4.3             Yes
3       NaN              No
4       3.6              No
..      ...             ...
500     3.5              No
501     3.6              No
502     3.3              No
503     4.4             Yes
504     3.0              No

[505 rows x 2 columns]

In [13]:
# df['no_of_days_in_company']
df['join_date'] = pd.to_datetime(df['join_date'],format = 'mixed')
# df['days_since_joining'] = (pd.Timestamp.now() - df['join_date']).dt.days

df['days_since_joining'] = df['join_date'].apply(lambda date: (pd.Timestamp.now() - date).days)
df['years_since_joining'] = df['days_since_joining'] // 365
df[['join_date','days_since_joining','years_since_joining']]

     join_date  days_since_joining  years_since_joining
0   2024-04-25                 747                    2
1   2016-05-24                3640                    9
2   2017-06-28                3240                    8
3   2015-11-03                3843                   10
4   2021-04-03                1865                    5
..         ...                 ...                  ...
500 2019-09-10                2436                    6
501 2021-04-03                1865                    5
502 2018-03-16                2979                    8
503 2023-05-11                1097                    3
504 2019-08-20                2457                    6

[505 rows x 3 columns]