In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("employees.csv")
df['salary'] =df['salary'].fillna(0).astype(int)

#bins are (left, right] meaning that the left edge is exclusive and the right edge is inclusive.
#(0,40000] ->  greater than 0 and <= 40000 

bins = [0,40000,70000,100000,150000,300000]
labels = ['Very Low', 'Low', 'Medium', 'High', 'Very High']

df['salary_level']= pd.cut(df['salary'], bins=bins, labels=labels,right = False)
# if right = False then the bins are [left, right) meaning that the left edge is inclusive and the right edge is exclusive.
df[['salary','salary_level']]

     salary salary_level
0    133646         High
1     81835       Medium
2     42051          Low
3     72798       Medium
4     91113       Medium
..      ...          ...
500   55135          Low
501   91113       Medium
502   55060          Low
503   88299       Medium
504  137886         High

[505 rows x 2 columns]

In [6]:
# using qcut
'''
low->0
-10000
-20000
-30000
highest -> 400000

-> means equal intervals

q1,q2,q3,q4

'''

salary_quartiles = pd.qcut(df['salary'],q=4,labels=['Q1','Q2','Q3','Q4'])
df['salary_quartiles'] = salary_quartiles
df[['salary','salary_level', 'salary_quartiles']]

     salary salary_level salary_quartiles
0    133646         High               Q4
1     81835       Medium               Q3
2     42051          Low               Q1
3     72798       Medium               Q2
4     91113       Medium               Q3
..      ...          ...              ...
500   55135          Low               Q2
501   91113       Medium               Q3
502   55060          Low               Q2
503   88299       Medium               Q3
504  137886         High               Q4

[505 rows x 3 columns]