In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv("employees.csv")
df['salary'] = df['salary'].fillna(0).astype(int)
df['salary_rank'] = df['salary'].rank(ascending=False) #default is ascending
new_df = df.sort_values('salary_rank')
new_df[['emp_id', 'salary', 'salary_rank']]

     emp_id  salary  salary_rank
111    1112  218890          1.0
298    1299  218345          2.0
30     1031  216954          3.0
425    1426  216829          4.0
450    1451  215521          5.0
..      ...     ...          ...
287    1288       0        492.5
22     1023       0        492.5
382    1383    -999        504.0
397    1398    -999        504.0
468    1469    -999        504.0

[505 rows x 3 columns]

In [5]:
#using dense -> dense use the same rank for the same value and does not skip the next rank.
df['salary_rank_dense'] = df['salary'].rank(method='dense', ascending=False)
new_df = df.sort_values('salary_rank_dense')
new_df[['emp_id', 'salary', 'salary_rank_dense', 'salary_rank']]

     emp_id  salary  salary_rank_dense  salary_rank
111    1112  218890                1.0          1.0
298    1299  218345                2.0          2.0
30     1031  216954                3.0          3.0
425    1426  216829                4.0          4.0
450    1451  215521                5.0          5.0
..      ...     ...                ...          ...
287    1288       0              478.0        492.5
22     1023       0              478.0        492.5
382    1383    -999              479.0        504.0
397    1398    -999              479.0        504.0
468    1469    -999              479.0        504.0

[505 rows x 4 columns]

In [6]:
# method = 'first' -> assigns ranks in the order they appear in the array. This is the default method.
# method = 'min' -> assigns the minimum rank to all the tied values.
# method = 'max' -> assigns the maximum rank to all the tied values.
# method = 'dense' -> assigns ranks in the order they appear in the array, but skips the next rank if the value is the same.

In [7]:
#Engineering department me salaey basics par rank karna hai

df['dept_salary_rank'] = df.groupby('department')['salary'].rank(ascending=False,method='dense')
df[['emp_id','salary','department','dept_salary_rank']].sort_values(['department','dept_salary_rank'])

     emp_id  salary   department  dept_salary_rank
446    1447   87702  ENGINEERING               1.0
450    1451  215521  Engineering               1.0
498    1499  213644  Engineering               2.0
167    1168  207200  Engineering               3.0
62     1063  202502  Engineering               4.0
..      ...     ...          ...               ...
262    1263   88624          NaN               NaN
291    1292   99427          NaN               NaN
306    1307  139493          NaN               NaN
459    1460   85204          NaN               NaN
499    1500  110504          NaN               NaN

[505 rows x 4 columns]