In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('dirty_cafe_sales.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
#2find total number of missing values in entire dataframe and in each column

df.isnull().sum().sum()
#3.for each column percentage of missing values -> loction has highest
missing_percentage = df.isnull().sum()/len(df)*100
print(missing_percentage)

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [7]:
#4. Display all rows which have at least one missing value
missing_values = df[df.isnull().any(axis=1)]
print(missing_values)

     Transaction ID      Item Quantity Price Per Unit Total Spent  \
5       TXN_2602893  Smoothie        5            4.0        20.0
8       TXN_4717867       NaN        5            3.0        15.0
9       TXN_2064365  Sandwich        5            4.0        20.0
13      TXN_9437049    Cookie        5            1.0         5.0
14      TXN_8915701     ERROR        2            1.5         3.0
...             ...       ...      ...            ...         ...
9994    TXN_7851634   UNKNOWN        4            4.0        16.0
9995    TXN_7672686    Coffee        2            2.0         4.0
9996    TXN_9659401       NaN        3            NaN         3.0
9997    TXN_5255387    Coffee        4            2.0         8.0
9998    TXN_7695629    Cookie        3            NaN         3.0

      Payment Method  Location Transaction Date
5        Credit Card       NaN       2023-03-31
8                NaN  Takeaway       2023-07-28
9                NaN  In-store       2023-12-31
13               NaN  Takeaway       2023-06-01
14               NaN  In-store       2023-03-21
...              ...       ...              ...
9994             NaN       NaN       2023-01-08
9995             NaN   UNKNOWN       2023-08-30
9996  Digital Wallet       NaN       2023-06-02
9997  Digital Wallet       NaN       2023-03-02
9998  Digital Wallet       NaN       2023-12-02

[5450 rows x 8 columns]

In [8]:
#5 find duplicates rows
duplicate_rows = df[df.duplicated()]
print(duplicate_rows)

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []

In [10]:
col = ['Quantity','Price Per Unit','Total Spent']
#replace multiple values with NaN
df[col] = df[col].replace(['ERROR','UNKNOWN'], np.nan)
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [11]:
df['Quantity'] = pd.to_numeric(df['Quantity'],errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'],errors='coerce')
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [12]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'],errors = 'coerce')
df.dtypes

Transaction ID              object
Item                        object
Quantity                   float64
Price Per Unit              object
Total Spent                float64
Payment Method              object
Location                    object
Transaction Date    datetime64[ns]
dtype: object

In [16]:

convert_dict = {'Item': 'category','Payment Method': 'category','Location': 'category'}
df = df.astype(convert_dict)
df.info(memory_usage= 'deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   category
 2   Quantity          9521 non-null   float64
 3   Price Per Unit    9467 non-null   object
 4   Total Spent       9498 non-null   float64
 5   Payment Method    7421 non-null   category
 6   Location          6735 non-null   category
 7   Transaction Date  9540 non-null   datetime64[ns]
dtypes: category(3), datetime64[ns](1), float64(2), object(2)
memory usage: 1.3 MB

In [19]:
df['Payment Method'] = df['Payment Method'].fillna(df['Payment Method'].mode()[0])  #fill with most frequent value
#fill the location with most frequent value
df['Location'] = df['Location'].fillna(df['Location'].mode()[0])
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())  #fill with median value
df.isnull().sum()

Transaction ID        0
Item                333
Quantity              0
Price Per Unit      533
Total Spent         502
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [21]:
df['Item'] = df['Item'].str.strip().str.title()
df['Item'] = df['Item'].fillna(df['Item'].mode()[0])
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [22]:
df.isnull().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit      533
Total Spent         502
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [23]:
#drop all missing values
df.dropna(inplace = True)
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [31]:
rename_columns = {'Transaction ID': 'txn_id','Transaction Date':'txn_date','Price Per Unit':'price_per_unit','Total Spent':'total_spent','Payment Method':'payment_method'}
df.rename(columns = rename_columns,inplace = True)
# 
df.head()

,txn_id,Item,quantity,price_per_unit,total_spent,payment_method,location,txn_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,TAKEAWAY,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,IN-STORE,2023-05-16
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,IN-STORE,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,TAKEAWAY,2023-03-31

In [30]:
#make sure location and Quantity column name are in lower case
df.rename(columns = {'Location':'location','Quantity':'quantity'},inplace = True)
df.head()

,txn_id,Item,quantity,price_per_unit,total_spent,payment_method,location,txn_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,TAKEAWAY,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,IN-STORE,2023-05-16
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,IN-STORE,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,TAKEAWAY,2023-03-31