# List Comprehension

Definition

Ek concise (chhoti aur readable) syntax jo list banane ke liye use hoti hai.

Basically ek for loop + optional condition ko ek line me likhne ka tareeka.

### Syntax -> [expression for item in iterable if condition]
expression → kya banana hai

item → ek-ek element of iterable

iterable → list, tuple, dict, pandas column, etc.

if condition → optional (filter karne ke liye)

In [1]:
nums = [1, 2, 3, 4]
squares = [x*x for x in nums]
print(squares)

[1, 4, 9, 16]

In [2]:
nums = [1, 2, 3, 4, 5]
evens = [x for x in nums if x % 2 == 0]
print(evens)   # [2, 4]

[2, 4]

In [3]:
pairs = [(x,y) for x in [1,2] for y in ['a','b']]
print(pairs)

[(1, 'a'), (1, 'b'), (2, 'a'), (2, 'b')]

In [5]:
data = ["apple", "", "banana", None, "grape"]
cleaned = [i for i in data if i]  
print(cleaned)  # ['apple', 'banana', 'grape']

['apple', 'banana', 'grape']

### Pandas me List Comprehension

Pandas me mostly tum columns ko transform karne ke liye ya naye column banane ke liye
list comprehension use karte ho.

In [2]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['Aparichit', 'Rohit', 'Sita'],
    'Age': [25, 30, 28]
})

df['AgeCat'] = ['Young' if age < 26 else 'Adult' for age in df['Age']]
print(df)

        Name  Age AgeCat
0  Aparichit   25  Young
1      Rohit   30  Adult
2       Sita   28  Adult

In [8]:
df['AgeCat'] = df['Age'].apply(lambda x:'Young' if x<=28 else 'Adult')
df

        Name  Age AgeCat
0  Aparichit   25  Young
1      Rohit   30  Adult
2       Sita   28  Young

#### Multiple columns combine

In [3]:
df['Info'] = [f"{n}-{a}" for n ,a in zip(df['Name'],df["Age"])]
print(df)

        Name  Age AgeCat          Info
0  Aparichit   25  Young  Aparichit-25
1      Rohit   30  Adult      Rohit-30
2       Sita   28  Adult       Sita-28

In [10]:
# List of only adults
adults = [name for name, age in zip(df['Name'], df['Age']) if age >= 28]
print(adults)  # ['Rohit', 'Sita']

['Rohit', 'Sita']

In [4]:
def age_bracket(age):
    if age < 26:
        return "Junior"
    elif age < 30:
        return "Mid"
    else:
        return "Senior"

df['Bracket'] = [age_bracket(a) for a in df['Age']]
print(df)

        Name  Age AgeCat          Info Bracket
0  Aparichit   25  Young  Aparichit-25  Junior
1      Rohit   30  Adult      Rohit-30  Senior
2       Sita   28  Adult       Sita-28     Mid

In [5]:
df['post'] = ['young_1' if age <26 else 'Adult_1' if age < 30 else 'Senior_1' for age in df['Age']]
df

        Name  Age AgeCat          Info Bracket      post
0  Aparichit   25  Young  Aparichit-25  Junior   young_1
1      Rohit   30  Adult      Rohit-30  Senior  Senior_1
2       Sita   28  Adult       Sita-28     Mid   Adult_1