In [1]:
square = lambda x : x**2
square(5)

25

In [6]:
nums = [1,2,3,4]
squares= list(map(lambda x:x**2,nums))
squares

[1, 4, 9, 16]

In [3]:
nums = [1,2,3,4]
squar1 = [i**2 for i in nums]
squar1

[1, 4, 9, 16]

In [6]:
#filter
vol = [11,22,33,44,55,66,77,88]
even = list(filter(lambda x:x%2 == 0,vol))
even

[22, 44, 66, 88]

In [7]:
from functools import reduce

In [10]:
nums2 = [1,2,3,4]
prod = reduce(lambda acc,x:acc+x,nums2,100)
prod

110

In [16]:
#in pandas

In [19]:
import pandas as pd
df = pd.DataFrame({'Name': ['Aparichit','Rohit','Sita'], 'Age': [25, 30, 28]})
df['AgeCat'] = df['Age'].apply(lambda x:"young" if x<26 else "adult",) 
df

        Name  Age AgeCat
0  Aparichit   25  young
1      Rohit   30  adult
2       Sita   28  adult

In [14]:
# row wise

In [15]:
df["Tag"] = df.apply(lambda r:f"{r['Name']}-{r['Age']}",axis = 1)
df

        Name  Age AgeCat           Tag
0  Aparichit   25  young  Aparichit-25
1      Rohit   30  adult      Rohit-30
2       Sita   28  adult       Sita-28