## 1) Basics of Indexing in Pandas
DataFrame ke paas row index aur column labels hote hain.
Do tarike hote hain data access karne ke:

##### Label-based → .loc[]
##### Position-based → .iloc[]

In [1]:
import pandas as pd
df = pd.read_csv("employees.csv")

In [2]:
print(df.dtypes)

EmpID           int64
Name           object
JoiningDate    object
Salary          int64
Department     object
dtype: object

In [3]:
print(df["Department"].memory_usage(deep=True))

555

In [4]:
df["Department"] = df["Department"].astype("category")
print(df["Department"].memory_usage(deep=True))

406

In [5]:
df["EmpID"] = df["EmpID"].astype("int32")
df["Salary"] = df["Salary"].astype("float32")
df["JoiningDate"] = pd.to_datetime(df["JoiningDate"])

In [6]:
df.dtypes

EmpID                   int32
Name                   object
JoiningDate    datetime64[ns]
Salary                float32
Department           category
dtype: object

### .loc[] → Label-based Selection

In [7]:
df.head(5)

   EmpID   Name JoiningDate   Salary Department
0      1   Ravi  2021-05-10  50000.0         IT
1      2   Sita  2022-07-15  60000.0         HR
2      3   Amit  2021-08-01  55000.0    Finance
3      4   Neha  2023-01-20  48000.0         IT
4      5  Arjun  2020-11-11  75000.0    Finance

In [16]:
# a) Single row by index label
df.loc[2]

EmpID                            3
Name                          Amit
JoiningDate    2021-08-01 00:00:00
Salary                     55000.0
Department                 Finance
Name: 2, dtype: object

In [18]:
# b) Multiples row
df.loc[[1,3,5]]

   EmpID   Name JoiningDate   Salary Department
1      2   Sita  2022-07-15  60000.0         HR
3      4   Neha  2023-01-20  48000.0         IT
5      6  Meera  2019-03-25  42000.0         HR

In [10]:
# Specific row & column

In [11]:
df.loc[2, "Name"]

'Amit'

In [12]:
#Multiple rows & columns

In [13]:
df.loc[[1, 3], ["Name", "Salary"]]

   Name   Salary
1  Sita  60000.0
3  Neha  48000.0

In [14]:
#Conditional selection with loc
df.loc[df["Department"] == "IT",["Name","Salary"]]

    Name   Salary
0   Ravi  50000.0
3   Neha  48000.0
6  Karan  58000.0

### .iloc[] → Position-based Selection

In [19]:
#Single row by position

In [20]:
df.iloc[0]

EmpID                            1
Name                          Ravi
JoiningDate    2021-05-10 00:00:00
Salary                     50000.0
Department                      IT
Name: 0, dtype: object

In [23]:
df.iloc[[0, 2, 3]]

   EmpID  Name JoiningDate   Salary Department
0      1  Ravi  2021-05-10  50000.0         IT
2      3  Amit  2021-08-01  55000.0    Finance
3      4  Neha  2023-01-20  48000.0         IT

In [24]:
# Row & Column both

In [25]:
df.iloc[1, 2]

Timestamp('2022-07-15 00:00:00')

In [26]:
df.head(4)

   EmpID  Name JoiningDate   Salary Department
0      1  Ravi  2021-05-10  50000.0         IT
1      2  Sita  2022-07-15  60000.0         HR
2      3  Amit  2021-08-01  55000.0    Finance
3      4  Neha  2023-01-20  48000.0         IT

In [27]:
#Range slicing

In [29]:
df.iloc[0:3,1:3]

   Name JoiningDate
0  Ravi  2021-05-10
1  Sita  2022-07-15
2  Amit  2021-08-01

### Slicing with Index

In [31]:
# Row slicing (works on labels if index sorted)

In [32]:
df.loc[1:2]

   EmpID  Name JoiningDate   Salary Department
1      2  Sita  2022-07-15  60000.0         HR
2      3  Amit  2021-08-01  55000.0    Finance

In [33]:
#Column slicing

In [36]:
df.loc[:, "Name":"Salary"].head(5)

    Name JoiningDate   Salary
0   Ravi  2021-05-10  50000.0
1   Sita  2022-07-15  60000.0
2   Amit  2021-08-01  55000.0
3   Neha  2023-01-20  48000.0
4  Arjun  2020-11-11  75000.0

In [38]:
# Mixed slicing (rows + cols)     Edge Cases & Pitfalls
                                   #.loc includes end index in slicing
df.loc[2:4, "Name":"Department"]

    Name JoiningDate   Salary Department
2   Amit  2021-08-01  55000.0    Finance
3   Neha  2023-01-20  48000.0         IT
4  Arjun  2020-11-11  75000.0    Finance

In [39]:
df.head(5)

   EmpID   Name JoiningDate   Salary Department
0      1   Ravi  2021-05-10  50000.0         IT
1      2   Sita  2022-07-15  60000.0         HR
2      3   Amit  2021-08-01  55000.0    Finance
3      4   Neha  2023-01-20  48000.0         IT
4      5  Arjun  2020-11-11  75000.0    Finance

In [43]:
df.loc[(df["Department"] == "HR"), ["Name", "Salary"]]

    Name   Salary
1   Sita  60000.0
5  Meera  42000.0

In [44]:
df['SalaryWithBonus'] = df['Salary'] * 1.10
df

   EmpID   Name JoiningDate   Salary Department  SalaryWithBonus
0      1   Ravi  2021-05-10  50000.0         IT          55000.0
1      2   Sita  2022-07-15  60000.0         HR          66000.0
2      3   Amit  2021-08-01  55000.0    Finance          60500.0
3      4   Neha  2023-01-20  48000.0         IT          52800.0
4      5  Arjun  2020-11-11  75000.0    Finance          82500.0
5      6  Meera  2019-03-25  42000.0         HR          46200.0
6      7  Karan  2021-12-05  58000.0         IT          63800.0
7      8  Pooja  2022-09-30  67000.0    Finance          73700.0

In [45]:
df.loc[5,"Salary"]

42000.0

In [46]:
df.loc[3]

EmpID                                4
Name                              Neha
JoiningDate        2023-01-20 00:00:00
Salary                         48000.0
Department                          IT
SalaryWithBonus                52800.0
Name: 3, dtype: object

In [47]:
df.loc[[1,5],["Name", "Salary"]]

    Name   Salary
1   Sita  60000.0
5  Meera  42000.0

In [49]:
df.loc[1:4,["Name", "Salary"]]

    Name   Salary
1   Sita  60000.0
2   Amit  55000.0
3   Neha  48000.0
4  Arjun  75000.0

In [50]:
df.loc[(df["Department"]=="IT"),["Name", "Salary"]]

    Name   Salary
0   Ravi  50000.0
3   Neha  48000.0
6  Karan  58000.0

In [52]:
df.iloc[[2,4]]["Salary"]

2    55000.0
4    75000.0
Name: Salary, dtype: float32