In [3]:
import pandas as pd
import numpy as np

# Sample data
data = {
    "EmpID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Name": ["Ravi", "Sita", "Amit", "Neha", "Arjun", "Meera", "Karan", "Pooja"],
    "JoiningDate": [
        "2021-05-10", "2022-07-15", "2021-08-01", "2023-01-20",
        "2020-11-11", "2019-03-25", "2021-12-05", "2022-09-30"
    ],
    "Salary": [50000, 60000, 55000, 48000, 75000, 42000, 58000, 67000],
    "Department": ["IT", "HR", "Finance", "IT", "Finance", "HR", "IT", "Finance"],
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Adding Age column with random values between 22 and 60
df["Age"] = np.random.randint(22, 60, size=len(df))

# Adding more rows
new_data = {
    "EmpID": [9, 10],
    "Name": ["Raj", "Simi"],
    "JoiningDate": ["2022-10-20", "2021-04-11"],
    "Salary": [53000, 59000],
    "Department": ["IT", "HR"],
    "Age": [32, 45],
}

# Convert new data to DataFrame and append to existing data
new_df = pd.DataFrame(new_data)
df = pd.concat([df, new_df], ignore_index=True)

# Save to CSV
df.to_csv("employees_new.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [4]:
df = pd.read_csv("employees_new.csv")
df

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   32
1      2   Sita  2022-07-15   60000         HR   50
2      3   Amit  2021-08-01   55000    Finance   22
3      4   Neha  2023-01-20   48000         IT   32
4      5  Arjun  2020-11-11   75000    Finance   26
5      6  Meera  2019-03-25   42000         HR   53
6      7  Karan  2021-12-05   58000         IT   24
7      8  Pooja  2022-09-30   67000    Finance   48
8      9    Raj  2022-10-20   53000         IT   32
9     10   Simi  2021-04-11   59000         HR   45

## Boolean Indexing Basics
##### Boolean indexing matlab ek True/False mask create karke uske basis pe rows filter karna.

In [6]:
df["Age"] > 30

0    False
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
Name: Age, dtype: bool

### Single Condition Filtering

In [6]:
df[df["Age"] > 30]

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   56
1      2   Sita  2022-07-15   60000         HR   39
2      3   Amit  2021-08-01   55000    Finance   37
3      4   Neha  2023-01-20   48000         IT   49
4      5  Arjun  2020-11-11   75000    Finance   34
6      7  Karan  2021-12-05   58000         IT   59
7      8  Pooja  2022-09-30   67000    Finance   54
8      9    Raj  2022-10-20   53000         IT   32
9     10   Simi  2021-04-11   59000         HR   45

In [8]:
df[df["Salary"]>55000]

   EmpID   Name JoiningDate  Salary Department  Age
1      2   Sita  2022-07-15   60000         HR   39
4      5  Arjun  2020-11-11   75000    Finance   34
6      7  Karan  2021-12-05   58000         IT   59
7      8  Pooja  2022-09-30   67000    Finance   54
9     10   Simi  2021-04-11   59000         HR   45

##### Multiple Conditions
###### Important: Conditions ko ()` bracket ke andar likhna zaruri hai, warna error aayega.

In [10]:
df[(df["Age"] > 25) & (df["Department"] == "HR")]

   EmpID   Name JoiningDate  Salary Department  Age
1      2   Sita  2022-07-15   60000         HR   39
5      6  Meera  2019-03-25   42000         HR   29
9     10   Simi  2021-04-11   59000         HR   45

In [11]:
df[(df["Department"] == "HR") | (df["Department"] == "IT")]

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   56
1      2   Sita  2022-07-15   60000         HR   39
3      4   Neha  2023-01-20   48000         IT   49
5      6  Meera  2019-03-25   42000         HR   29
6      7  Karan  2021-12-05   58000         IT   59
8      9    Raj  2022-10-20   53000         IT   32
9     10   Simi  2021-04-11   59000         HR   45

In [12]:
df[~(df["Department"] == "Finance")]

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   56
1      2   Sita  2022-07-15   60000         HR   39
3      4   Neha  2023-01-20   48000         IT   49
5      6  Meera  2019-03-25   42000         HR   29
6      7  Karan  2021-12-05   58000         IT   59
8      9    Raj  2022-10-20   53000         IT   32
9     10   Simi  2021-04-11   59000         HR   45

In [5]:
import pandas as pd

data = {
    "CustomerID": [1, 2, 3, 4, 5, 6],
    "Name": ["Ravi", "Sita", "Amit", "Neha", "Kiran", "Pooja"],
    "Age": [25, 40, 32, 29, 35, 42],
    "City": ["Delhi", "Mumbai", "Delhi", "Delhi", "Bangalore", "Delhi"]
}

df = pd.DataFrame(data)
print(df)

   CustomerID   Name  Age       City
0           1   Ravi   25      Delhi
1           2   Sita   40     Mumbai
2           3   Amit   32      Delhi
3           4   Neha   29      Delhi
4           5  Kiran   35  Bangalore
5           6  Pooja   42      Delhi

Extra Filtering Tricks

#### isin() → multiple values filter

In [6]:
df[df["City"].isin(["Delhi","Mumbai"])]

   CustomerID   Name  Age    City
0           1   Ravi   25   Delhi
1           2   Sita   40  Mumbai
2           3   Amit   32   Delhi
3           4   Neha   29   Delhi
5           6  Pooja   42   Delhi

### Large datasets ke liye multiple filters chain karne ki jagah ek hi .query() use kar sakte ho:

In [7]:
df.query("Age > 30 and City == 'Delhi'")

   CustomerID   Name  Age   City
2           3   Amit   32  Delhi
5           6  Pooja   42  Delhi

In [16]:
result = df[(df["Age"] > 30) & (df["City"] == "Delhi")]
print(result)

   CustomerID   Name  Age   City
2           3   Amit   32  Delhi
5           6  Pooja   42  Delhi

In [8]:
df.query("Age < 35 and City == 'Delhi'")

   CustomerID  Name  Age   City
0           1  Ravi   25  Delhi
2           3  Amit   32  Delhi
3           4  Neha   29  Delhi

In [15]:
df[df["City"].str.contains('a')]

   CustomerID   Name  Age       City
1           2   Sita   40     Mumbai
4           5  Kiran   35  Bangalore