In [1]:
import pandas as pd

In [36]:
df = pd.read_csv("employees_new.csv")

In [37]:
df

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   55
1      2   Sita  2022-07-15   60000         HR   52
2      3   Amit  2021-08-01   55000    Finance   56
3      4   Neha  2023-01-20   48000         IT   23
4      5  Arjun  2020-11-11   75000    Finance   22
5      6  Meera  2019-03-25   42000         HR   55
6      7  Karan  2021-12-05   58000         IT   50
7      8  Pooja  2022-09-30   67000    Finance   22
8      9    Raj  2022-10-20   53000         IT   32
9     10   Simi  2021-04-11   59000         HR   45

# Sorting in Pandas

### sort_values() → Sort by column values

In [6]:
df.sort_values(by = "Salary")  #ascending order

   EmpID   Name JoiningDate  Salary Department  Age
5      6  Meera  2019-03-25   42000         HR   55
3      4   Neha  2023-01-20   48000         IT   23
0      1   Ravi  2021-05-10   50000         IT   55
8      9    Raj  2022-10-20   53000         IT   32
2      3   Amit  2021-08-01   55000    Finance   56
6      7  Karan  2021-12-05   58000         IT   50
9     10   Simi  2021-04-11   59000         HR   45
1      2   Sita  2022-07-15   60000         HR   52
7      8  Pooja  2022-09-30   67000    Finance   22
4      5  Arjun  2020-11-11   75000    Finance   22

In [8]:
df.sort_values(by = "Salary",ascending = False)

   EmpID   Name JoiningDate  Salary Department  Age
4      5  Arjun  2020-11-11   75000    Finance   22
7      8  Pooja  2022-09-30   67000    Finance   22
1      2   Sita  2022-07-15   60000         HR   52
9     10   Simi  2021-04-11   59000         HR   45
6      7  Karan  2021-12-05   58000         IT   50
2      3   Amit  2021-08-01   55000    Finance   56
8      9    Raj  2022-10-20   53000         IT   32
0      1   Ravi  2021-05-10   50000         IT   55
3      4   Neha  2023-01-20   48000         IT   23
5      6  Meera  2019-03-25   42000         HR   55

In [10]:
#Multiple columns(Tie breaker)
df.sort_values(by=["Department", "Salary"], ascending=[True, False])

   EmpID   Name JoiningDate  Salary Department  Age
4      5  Arjun  2020-11-11   75000    Finance   22
7      8  Pooja  2022-09-30   67000    Finance   22
2      3   Amit  2021-08-01   55000    Finance   56
1      2   Sita  2022-07-15   60000         HR   52
9     10   Simi  2021-04-11   59000         HR   45
5      6  Meera  2019-03-25   42000         HR   55
6      7  Karan  2021-12-05   58000         IT   50
8      9    Raj  2022-10-20   53000         IT   32
0      1   Ravi  2021-05-10   50000         IT   55
3      4   Neha  2023-01-20   48000         IT   23

### sort_index() → Sort by row/column index

In [11]:
df.sort_index()

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   55
1      2   Sita  2022-07-15   60000         HR   52
2      3   Amit  2021-08-01   55000    Finance   56
3      4   Neha  2023-01-20   48000         IT   23
4      5  Arjun  2020-11-11   75000    Finance   22
5      6  Meera  2019-03-25   42000         HR   55
6      7  Karan  2021-12-05   58000         IT   50
7      8  Pooja  2022-09-30   67000    Finance   22
8      9    Raj  2022-10-20   53000         IT   32
9     10   Simi  2021-04-11   59000         HR   45

In [38]:
df.sort_index(axis=1)   # Sort columns alphabetically

   Age Department  EmpID JoiningDate   Name  Salary
0   55         IT      1  2021-05-10   Ravi   50000
1   52         HR      2  2022-07-15   Sita   60000
2   56    Finance      3  2021-08-01   Amit   55000
3   23         IT      4  2023-01-20   Neha   48000
4   22    Finance      5  2020-11-11  Arjun   75000
5   55         HR      6  2019-03-25  Meera   42000
6   50         IT      7  2021-12-05  Karan   58000
7   22    Finance      8  2022-09-30  Pooja   67000
8   32         IT      9  2022-10-20    Raj   53000
9   45         HR     10  2021-04-11   Simi   59000

In [39]:
top5 = df.nlargest(5,"Salary")
top5

   EmpID   Name JoiningDate  Salary Department  Age
4      5  Arjun  2020-11-11   75000    Finance   22
7      8  Pooja  2022-09-30   67000    Finance   22
1      2   Sita  2022-07-15   60000         HR   52
9     10   Simi  2021-04-11   59000         HR   45
6      7  Karan  2021-12-05   58000         IT   50

In [46]:
bottom3 = df.nsmallest(3,"Salary")
bottom3

   EmpID   Name JoiningDate  Salary Department  Age
5      6  Meera  2019-03-25   42000         HR   55
3      4   Neha  2023-01-20   48000         IT   23
0      1   Ravi  2021-05-10   50000         IT   55

In [43]:
df1 = df.sample(frac = 0.2)
df1

   EmpID   Name JoiningDate  Salary Department  Age
9     10   Simi  2021-04-11   59000         HR   45
7      8  Pooja  2022-09-30   67000    Finance   22

In [44]:
df.sort_index(axis=1)

   Age Department  EmpID JoiningDate   Name  Salary
0   55         IT      1  2021-05-10   Ravi   50000
1   52         HR      2  2022-07-15   Sita   60000
2   56    Finance      3  2021-08-01   Amit   55000
3   23         IT      4  2023-01-20   Neha   48000
4   22    Finance      5  2020-11-11  Arjun   75000
5   55         HR      6  2019-03-25  Meera   42000
6   50         IT      7  2021-12-05  Karan   58000
7   22    Finance      8  2022-09-30  Pooja   67000
8   32         IT      9  2022-10-20    Raj   53000
9   45         HR     10  2021-04-11   Simi   59000

In [45]:
top3= df.nlargest(3,"Salary")
top3

   EmpID   Name JoiningDate  Salary Department  Age
4      5  Arjun  2020-11-11   75000    Finance   22
7      8  Pooja  2022-09-30   67000    Finance   22
1      2   Sita  2022-07-15   60000         HR   52

# Sampling in Pandas

#### Random sample of rows

In [15]:
df.sample(n=3)

   EmpID   Name JoiningDate  Salary Department  Age
1      2   Sita  2022-07-15   60000         HR   52
3      4   Neha  2023-01-20   48000         IT   23
7      8  Pooja  2022-09-30   67000    Finance   22

#### Fractional sampling

In [17]:
df.sample(frac=0.2)

   EmpID  Name JoiningDate  Salary Department  Age
0      1  Ravi  2021-05-10   50000         IT   55
2      3  Amit  2021-08-01   55000    Finance   56

In [21]:
# With replacement
df.sample(n=5, replace=True)

   EmpID   Name JoiningDate  Salary Department  Age
0      1   Ravi  2021-05-10   50000         IT   55
7      8  Pooja  2022-09-30   67000    Finance   22
4      5  Arjun  2020-11-11   75000    Finance   22
6      7  Karan  2021-12-05   58000         IT   50
7      8  Pooja  2022-09-30   67000    Finance   22

In [23]:
# Random state (reproducibility)
df.sample(n=3, random_state=42)

   EmpID   Name JoiningDate  Salary Department  Age
8      9    Raj  2022-10-20   53000         IT   32
1      2   Sita  2022-07-15   60000         HR   52
5      6  Meera  2019-03-25   42000         HR   55

#### Column-wise sample

In [28]:
df.sample(n=2, axis=1,random_state=42 )   # 2 random columns

   EmpID   Name
0      1   Ravi
1      2   Sita
2      3   Amit
3      4   Neha
4      5  Arjun
5      6  Meera
6      7  Karan
7      8  Pooja
8      9    Raj
9     10   Simi

# Practical Example DataFrame

In [29]:
import pandas as pd

data = {
    "OrderID": range(1, 11),
    "Customer": ["Ravi","Sita","Amit","Neha","Kiran","Pooja","Vikas","Rani","Arjun","Meena"],
    "Sales": [5000, 7000, 12000, 8000, 15000, 2000, 9500, 11000, 4000, 18000]
}

df = pd.DataFrame(data)
print(df)

   OrderID Customer  Sales
0        1     Ravi   5000
1        2     Sita   7000
2        3     Amit  12000
3        4     Neha   8000
4        5    Kiran  15000
5        6    Pooja   2000
6        7    Vikas   9500
7        8     Rani  11000
8        9    Arjun   4000
9       10    Meena  18000

In [30]:
top10 = df.sort_values(by="Sales",ascending = False).head(10)
top10

   OrderID Customer  Sales
9       10    Meena  18000
4        5    Kiran  15000
2        3     Amit  12000
7        8     Rani  11000
6        7    Vikas   9500
3        4     Neha   8000
1        2     Sita   7000
0        1     Ravi   5000
8        9    Arjun   4000
5        6    Pooja   2000

Performance Tip

Large datasets me top N fastest nikalne ke liye nlargest() aur nsmallest() use karo:

df.nlargest(10, "Sales")
df.nsmallest(5, "Sales")

In [34]:
df.nlargest(5, "Sales")

   OrderID Customer  Sales
9       10    Meena  18000
4        5    Kiran  15000
2        3     Amit  12000
7        8     Rani  11000
6        7    Vikas   9500

In [33]:
df.nsmallest(5, "Sales")

   OrderID Customer  Sales
5        6    Pooja   2000
8        9    Arjun   4000
0        1     Ravi   5000
1        2     Sita   7000
3        4     Neha   8000